/**************************************************************************************************************
*
*			通信协议命令(cmd)定义文件											(Created by Andor.Zhang in 2004.11)
*
**************************************************************************************************************/
#ifndef NETCOMMAND_H
#define NETCOMMAND_H

#define NET_PROTOCOL_ENCRYPT   1	// 网络协议是否加密（针对外挂的修改）
#define CMD_INVALID		       0	//无效命令
//＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
//                 协议命令定义(16bit)
//			命令定义传输方向标识(如CMD_CM_XXX中的CM)：
//				CM	(C)lient		->Ga(m)eServer
//				MC	Ga(m)eServer	->(C)lient
//						......
//				(其它见"协议命令基数定义"部分)
//	(注：每个方向的命令空间请预留500个，并且每个区间从1开始，如CMD_CM_BASE+1开始定义)
//	二级子协议定义推荐使用“MSG_”开始，如：MSG_TEAM_CANCLE_TIMEOUT;宽度为1字节(8bit)，使用WriteChar/ReadChar操作
//＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
/*=====================================================================================================
*					协议命令基数定义：
*/
#define CMD_CM_BASE			   0    // (C)lient       -> Ga(m)eServer
#define CMD_MC_BASE			 500    // Ga(m)eServer   -> (C)lient
#define CMD_TM_BASE			1000	// Ga(t)eServer   -> Ga(m)eServer
#define CMD_MT_BASE			1500	// Ga(m)eServer   -> Ga(t)eServer
#define CMD_TP_BASE         2000    // Ga(t)eServer   -> Grou(p)Server
#define CMD_PT_BASE         2500    // Grou(p)Server  -> Ga(t)eServer
#define CMD_PA_BASE         3000    // Grou(p)Server  -> (A)ccountServer
#define CMD_AP_BASE         3500    // (A)ccoutServer -> Grou(p)Server
#define CMD_MM_BASE			4000	// Ga(m)eServer	  -> Ga(m)eServer
#define CMD_PM_BASE         4500    // Grou(p)Server  -> Ga(m)eServer
#define	CMD_PC_BASE			5000	// Grou(p)Server  -> (C)lient
#define CMD_MP_BASE			5500	// Ga(m)eServer   -> Grou(p)Server
#define CMD_CP_BASE			6000	// (C)lient		  -> Grou(p)Server

// Add by lark.li 20081209 begin
#define CMD_OS_BASE			6500	// M(o)nitor	  -> (S)erver
#define CMD_SO_BASE			7000	//(S)erver		  ->  M(o)nitor
// End

// Add by lark.li 20090601 begin
#define CMD_AB_BASE			7500	// (A)ccoutServer -> (B)illingServer
#define CMD_BA_BASE			8000	// (B)illingServer-> (A)ccoutServer
// End

#include <map>
#include <string>
#include <utility>
using namespace std;

extern map<int, pair<string, string>> MsgMap;

inline void AddMessage(int id, const char* name, const char* description)
{
	if(MsgMap.find(id) != MsgMap.end())
		throw "The Same Message ID";

	MsgMap.insert(map<int, pair<string, string>>::value_type(id, make_pair<string, string>(name, description)));
}

inline string& GetMessageName(int id)
{
	map<int, pair<string, string>>::iterator it = MsgMap.find(id);

	if(it == MsgMap.end())
		throw "The Message ID not exsit";
	
	return it->second.first;
}

#define MESSAGE_DEF(name, id, description)		const int name = id;
#define MESSAGE_ADD(name, id, description)		AddMessage(id, "" #name  "", "" #description  "");
#define MESSAGE_NAME(id)						MsgMap[id].first
#define MESSAGE_DESC(id)						MsgMap[id].second
#define MESSAGE_NUM								MsgMap.size()

/*=====================================================================================================
*				(C)lient -> Ga(m)eServer
*/
MESSAGE_DEF(	CMD_CM_ROLEBASE,				CMD_CM_BASE + 300,	(300-400)任务系统命令基数)
MESSAGE_DEF(	CMD_CM_GULDBASE,				CMD_CM_BASE	+ 400,	(400-430)公会命令基址)
MESSAGE_DEF(	CMD_CM_CHARBASE,				CMD_CM_BASE	+ 430,	(430-450)角色命令基数)

MESSAGE_DEF(	CMD_CM_SAY,						CMD_CM_BASE + 1,	视野内说话)
MESSAGE_DEF(	CMD_CM_BEGINACTION,				CMD_CM_BASE + 6,	无)
	//char	行动类型（1，移动；2，使用技能；3，换装；4，靠椅子；5，上船）
	//	类型1：移动
	//		long	平均ping值
	//		Point	点序列（包含player的当前位置）
	//	类型2：使用技能
	//		char	技能子类型（1，直接使用；2，先移动再使用）
	//			类型1：直接使用
	//				long	技能编号（0，物理攻击；其他，技能ID）
	//				技能参数，根据技能的类型（个体，范围）选择下列参数
	//				long	目标ID
	//				Point	目标位置
	//			类型2：先移动再使用
	//				long	平均ping值
	//				Point	点序列（包含player的当前位置）
	//				long	技能编号（0，物理攻击；其他，技能ID）
	//				技能参数，根据技能的类型（个体，范围）选择下列参数
	//				long	目标ID
	//				Point	目标位置
	//	类型3：换装
	//	类型4：
	//	类型5：上船
	//		ulong	船的ID，如果为0，表示上船不成功
	//	类型6：下船
	//		char	0，下船不成功。1，下船成功

MESSAGE_DEF(	CMD_CM_ENDACTION,				CMD_CM_BASE + 7,	无)
MESSAGE_DEF(	CMD_CM_SYNATTR,					CMD_CM_BASE + 8,	同步角色属性（同步属性的最终值）)
MESSAGE_DEF(	CMD_CM_SYNSKILLBAG,				CMD_CM_BASE + 9,	同步技能栏)
MESSAGE_DEF(	CMD_CM_DIE_RETURN,				CMD_CM_BASE + 10,	死亡复活)
MESSAGE_DEF(	CMD_CM_SKILLUPGRADE,			CMD_CM_BASE + 11,	无)
MESSAGE_DEF(	CMD_CM_PING,					CMD_CM_BASE + 15,	无)
MESSAGE_DEF(	CMD_CM_REFRESH_DATA,			CMD_CM_BASE + 16,	无)
MESSAGE_DEF(	CMD_CM_CHECK_PING,				CMD_CM_BASE + 17,	计算Ping)
MESSAGE_DEF(	CMD_CM_MAP_MASK,				CMD_CM_BASE + 18,	无)

MESSAGE_DEF(	CMD_CM_UPDATEHAIR,				CMD_CM_BASE + 20,	客户端请求更换发型)
MESSAGE_DEF(	CMD_CM_TEAM_FIGHT_ASK,			CMD_CM_BASE + 21,	队伍挑战请求)
MESSAGE_DEF(	CMD_CM_TEAM_FIGHT_ASR,			CMD_CM_BASE + 22,	队伍挑战应答(ANSWER))
MESSAGE_DEF(	CMD_CM_ITEM_REPAIR_ASK,			CMD_CM_BASE + 23,	道具修理请求)
MESSAGE_DEF(	CMD_CM_ITEM_REPAIR_ASR,			CMD_CM_BASE + 24,	道具修理应答)
MESSAGE_DEF(	CMD_CM_ITEM_FORGE_ASK,			CMD_CM_BASE + 25,	道具精炼请求)
MESSAGE_DEF(	CMD_CM_ITEM_FORGE_ASR,			CMD_CM_BASE + 26,	道具精炼应答)
MESSAGE_DEF(	CMD_CM_TIGER_START,				CMD_CM_BASE + 27,	开启老虎机)
MESSAGE_DEF(	CMD_CM_TIGER_STOP,				CMD_CM_BASE + 28,	停止老虎机)
//行动
MESSAGE_DEF(	CMD_CM_ITEM_FORGE_CANACTION,	CMD_CM_BASE + 29,	有特殊任务已完成，可以做别的事。)
//背包锁定
MESSAGE_DEF(	CMD_CM_KITBAG_LOCK,				CMD_CM_BASE + 31,	背包锁定请求)
MESSAGE_DEF(	CMD_CM_KITBAG_UNLOCK,			CMD_CM_BASE + 32,	背包解锁请求)
MESSAGE_DEF(	CMD_CM_KITBAG_CHECK,			CMD_CM_BASE + 33,	检查背包锁定状态)
MESSAGE_DEF(	CMD_CM_KITBAG_AUTOLOCK,			CMD_CM_BASE + 34,	下线自动锁定)
MESSAGE_DEF(	CMD_CM_KITBAGTEMP_SYNC,			CMD_CM_BASE + 35,	同步临时背包)

//商城系统
MESSAGE_DEF(	CMD_CM_STORE_OPEN_ASK,			CMD_CM_BASE + 41,	打开商城)
MESSAGE_DEF(	CMD_CM_STORE_LIST_ASK,			CMD_CM_BASE + 42,	商城列表)
MESSAGE_DEF(	CMD_CM_STORE_BUY_ASK,			CMD_CM_BASE + 43,	购买道具)
MESSAGE_DEF(	CMD_CM_STORE_CHANGE_ASK,		CMD_CM_BASE + 44,	兑换代币)
MESSAGE_DEF(	CMD_CM_STORE_QUERY,				CMD_CM_BASE + 45,	交易记录查询)
MESSAGE_DEF(	CMD_CM_STORE_VIP,				CMD_CM_BASE + 46,	VIP)
MESSAGE_DEF(	CMD_CM_STORE_AFFICHE,			CMD_CM_BASE + 47,	公告商品)
MESSAGE_DEF(	CMD_CM_STORE_CLOSE,				CMD_CM_BASE + 48,	无)

//黑市商人
MESSAGE_DEF(	CMD_CM_BLACKMARKET_EXCHANGE_REQ,CMD_CM_BASE + 51,	黑市兑换)
MESSAGE_DEF(	CMD_CM_CHEAT_CHECK,				CMD_CM_BASE + 52,	无)

//老手带新手
MESSAGE_DEF(	CMD_CM_VOLUNTER_LIST,			CMD_CM_BASE + 61,	显示志愿者列表)
MESSAGE_DEF(	CMD_CM_VOLUNTER_ADD,			CMD_CM_BASE + 62,	添加到志愿者列表)
MESSAGE_DEF(	CMD_CM_VOLUNTER_DEL,			CMD_CM_BASE + 63,	从列表中删除)
MESSAGE_DEF(	CMD_CM_VOLUNTER_SEL,			CMD_CM_BASE + 64,	申请组队)
MESSAGE_DEF(	CMD_CM_VOLUNTER_OPEN,			CMD_CM_BASE + 65,	打开志愿者面板)
MESSAGE_DEF(	CMD_CM_VOLUNTER_ASR,			CMD_CM_BASE + 66,	志愿者组队应答)

//拜师
MESSAGE_DEF(	CMD_CM_MASTER_INVITE,			CMD_CM_BASE + 71,	拜师)
MESSAGE_DEF(	CMD_CM_MASTER_ASR,				CMD_CM_BASE + 72,	无)
MESSAGE_DEF(	CMD_CM_MASTER_DEL,				CMD_CM_BASE + 73,	无)
MESSAGE_DEF(	CMD_CM_PRENTICE_DEL,			CMD_CM_BASE + 74,	无)
MESSAGE_DEF(	CMD_CM_PRENTICE_INVITE,			CMD_CM_BASE + 75,	无)
MESSAGE_DEF(	CMD_CM_PRENTICE_ASR,			CMD_CM_BASE + 76,	无)

//生活技能
MESSAGE_DEF(	CMD_CM_LIFESKILL_ASR,			CMD_CM_BASE + 80,	生活技能用运，合成，分解等的请求)
MESSAGE_DEF(	CMD_CM_LIFESKILL_ASK,			CMD_CM_BASE + 81,	生活技能用运，合成，分解等的确认)

MESSAGE_DEF(	CMD_CM_BIDUP,					CMD_CM_BASE + 86,	无)

MESSAGE_DEF(	CMD_CM_SAY2CAMP,				CMD_CM_BASE + 91,	无)
MESSAGE_DEF(	CMD_CM_GM_SEND,					CMD_CM_BASE + 92,	无)
MESSAGE_DEF(	CMD_CM_GM_RECV,					CMD_CM_BASE + 93,	无)
MESSAGE_DEF(	CMD_CM_PK_CTRL,					CMD_CM_BASE + 94,	无)

// Add by lark.li 20080514 begin
MESSAGE_DEF(	CMD_CM_ITEM_LOTTERY_ASK,		CMD_CM_BASE + 95,	道具精炼请求)
MESSAGE_DEF(	CMD_CM_ITEM_LOTTERY_ASR,		CMD_CM_BASE + 96,	彩票设定应答)
// End

// Add by lark.li 20080707 begin
MESSAGE_DEF(	CMD_CM_CAPTAIN_CONFIRM_ASR,		CMD_CM_BASE + 97,	竞技场队长应答)
// End

MESSAGE_DEF(	CMD_CM_ITEM_AMPHITHEATER_ASK,	CMD_CM_BASE + 98,	投票发送)

//	2008-8-29	yangyinyu	add	begin!
MESSAGE_DEF(	CMD_CM_ITEM_LOCK_ASK,			CMD_CM_BASE	+ 99,	无)
//	2008-8-29	yangyinyu	add	end!
MESSAGE_DEF(	CMD_CM_ITEM_UNLOCK_ASK,			CMD_CM_BASE + 100,	无)

MESSAGE_DEF(    CMD_CM_SYNCHAR, CMD_CM_BASE + 101, SynChar)
MESSAGE_DEF(CMD_CM_GETORIGNAMECOLOR, CMD_CM_BASE + 102, GetOrigcolor)
MESSAGE_DEF(CMD_CM_CHANGETITLE, CMD_CM_BASE + 103, SetTitle)
MESSAGE_DEF(CMD_CM_SYNGUILDCOLOR, CMD_CM_BASE + 104, SynGuildColor)
//Begin 公会命令定义
	MESSAGE_DEF(	CMD_CM_GUILD_PUTNAME,		CMD_CM_GULDBASE	+ 1,	客户端输入公会名)
	MESSAGE_DEF(	CMD_CM_GUILD_TRYFOR,		CMD_CM_GULDBASE	+ 2,	申请加入公会)
	MESSAGE_DEF(	CMD_CM_GUILD_TRYFORCFM,		CMD_CM_GULDBASE	+ 3,	确认是否覆盖以前申请)
	MESSAGE_DEF(	CMD_CM_GUILD_LISTTRYPLAYER,	CMD_CM_GULDBASE	+ 4,	列出所有待批复玩家)

	MESSAGE_DEF(	CMD_CM_GUILD_APPROVE,		CMD_CM_GULDBASE	+ 5,	门猪批准申请人加入)
	MESSAGE_DEF(	CMD_CM_GUILD_REJECT,		CMD_CM_GULDBASE	+ 6,	门猪拒绝申请人加入)
	MESSAGE_DEF(	CMD_CM_GUILD_KICK,			CMD_CM_GULDBASE	+ 7,	无)
	MESSAGE_DEF(	CMD_CM_GUILD_LEAVE,			CMD_CM_GULDBASE	+ 8,	无)
	MESSAGE_DEF(	CMD_CM_GUILD_DISBAND,		CMD_CM_GULDBASE	+ 9,	无)
	MESSAGE_DEF(	CMD_CM_GUILD_MOTTO,			CMD_CM_GULDBASE	+ 10,	无)
	MESSAGE_DEF(	CMD_CM_GUILD_CHALLENGE,		CMD_CM_GULDBASE + 11,	挑战公会)
	MESSAGE_DEF(	CMD_CM_GUILD_LEIZHU,		CMD_CM_GULDBASE + 12,	抢擂主)
	MESSAGE_DEF(	CMD_CM_GUILD_PERM,			CMD_CM_GULDBASE + 13,	Guild Perm)
//End 公会命令定义

//Begin 角色操作和登录命令CMD_CM_CHARBASE
	MESSAGE_DEF(	CMD_CM_LOGIN,				CMD_CM_CHARBASE + 1,	用户帐号登入(用户名/密码对认证))
	MESSAGE_DEF(	CMD_CM_LOGOUT,				CMD_CM_CHARBASE + 2,	用户帐号登出)
	MESSAGE_DEF(	CMD_CM_BGNPLAY,				CMD_CM_CHARBASE + 3,	用户选择角色开始玩游戏)
	MESSAGE_DEF(	CMD_CM_ENDPLAY,				CMD_CM_CHARBASE + 4,	用户结束玩游戏进入选/建/删角色画面)
	MESSAGE_DEF(	CMD_CM_NEWCHA,				CMD_CM_CHARBASE	+ 5,	用户新建角色)
	MESSAGE_DEF(	CMD_CM_DELCHA,				CMD_CM_CHARBASE	+ 6,	用户删除角色)
	MESSAGE_DEF(	CMD_CM_CANCELEXIT,			CMD_CM_CHARBASE + 7,	用户要求取消退出)
//End 角色操作和登录命令

//Begin任务系统指令
	MESSAGE_DEF(	CMD_CM_REQUESTNPC,			CMD_CM_ROLEBASE + 1,	客户端请求和NPC互动)
	MESSAGE_DEF(	CMD_CM_REQUESTTALK,			CMD_CM_ROLEBASE + 1,	客户端请求与NPC对话命令)
	MESSAGE_DEF(	CMD_CM_TALKPAGE,			CMD_CM_ROLEBASE + 2,	客户端请求与NPC对话页命令)
	MESSAGE_DEF(	CMD_CM_FUNCITEM,			CMD_CM_ROLEBASE + 3,	客户端请求指定功能选项操作)

	MESSAGE_DEF(	CMD_CM_REQUESTTRADE,		CMD_CM_ROLEBASE + 8,	客户端请求进行交易)
	MESSAGE_DEF(	CMD_CM_TRADEITEM,			CMD_CM_ROLEBASE + 9,	客户端请求交易物品)
	MESSAGE_DEF(	CMD_CM_REQUESTAGENCY,		CMD_CM_ROLEBASE + 10,	客户端请求npc代理交易)

	//角色交易指令
	MESSAGE_DEF(	CMD_CM_CHARTRADE_REQUEST,	CMD_CM_ROLEBASE + 12,	发起交易邀请)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_ACCEPT,	CMD_CM_ROLEBASE + 13,	接受交易邀请)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_REJECT,	CMD_CM_ROLEBASE + 14,	拒绝交易邀请)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_CANCEL,	CMD_CM_ROLEBASE + 15,	取消交易)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_ITEM,		CMD_CM_ROLEBASE + 16,	角色交易物品)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_VALIDATEDATA,CMD_CM_ROLEBASE + 17,	确认交易数据)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_VALIDATE,	CMD_CM_ROLEBASE + 18,	确认交易)
	MESSAGE_DEF(	CMD_CM_CHARTRADE_MONEY,		CMD_CM_ROLEBASE + 19,	拖动金钱)

	// 任务
	MESSAGE_DEF(	CMD_CM_MISSION,				CMD_CM_ROLEBASE + 22,	客户端请求任务处理)
	MESSAGE_DEF(	CMD_CM_MISSIONLIST,			CMD_CM_ROLEBASE + 23,	任务列表)
	MESSAGE_DEF(	CMD_CM_MISSIONTALK,			CMD_CM_ROLEBASE + 24,	任务对话)
	MESSAGE_DEF(	CMD_CM_MISLOG,				CMD_CM_ROLEBASE + 25,	任务日志)
	MESSAGE_DEF(	CMD_CM_MISLOGINFO,			CMD_CM_ROLEBASE + 26,	单个任务详细信息)
	MESSAGE_DEF(	CMD_CM_MISLOG_CLEAR,		CMD_CM_ROLEBASE + 27,	亲求删除一个任务)
	
	// 摆摊
	MESSAGE_DEF(	CMD_CM_STALL_ALLDATA,		CMD_CM_ROLEBASE + 30,	请求摆摊数据信息)
	MESSAGE_DEF(	CMD_CM_STALL_OPEN,			CMD_CM_ROLEBASE + 31,	请求打开摆摊货物信息)
	MESSAGE_DEF(	CMD_CM_STALL_BUY,			CMD_CM_ROLEBASE + 32,	请求购买摆摊货物)
	MESSAGE_DEF(	CMD_CM_STALL_CLOSE,			CMD_CM_ROLEBASE + 33,	请求收摊)

	// 精练
// 	MESSAGE_DEF(	CMD_CM_FORGE			CMD_CM_ROLEBASE + 35 // 请求精练物品 //已无用 -Waiting Mark 2009-03-25

    
	// 船只
	MESSAGE_DEF(	CMD_CM_CREATE_BOAT,			CMD_CM_ROLEBASE + 38,	请求创建船)
	MESSAGE_DEF(	CMD_CM_UPDATEBOAT_PART,		CMD_CM_ROLEBASE + 39,	请求更换船只部件)
	MESSAGE_DEF(	CMD_CM_BOAT_CANCEL,			CMD_CM_ROLEBASE + 40,	请求取消建造船只)
	MESSAGE_DEF(	CMD_CM_BOAT_LUANCH,			CMD_CM_ROLEBASE + 41,	选择船只出海)
	MESSAGE_DEF(	CMD_CM_BOAT_BAGSEL,			CMD_CM_ROLEBASE + 42,	选择一艘船只货舱打包现有货物)
	MESSAGE_DEF(	CMD_CM_BOAT_SELECT,			CMD_CM_ROLEBASE + 43,	选择船只)
	MESSAGE_DEF(	CMD_CM_BOAT_GETINFO,		CMD_CM_ROLEBASE + 44,	获取船只信息)

	// 实体
	MESSAGE_DEF(	CMD_CM_ENTITY_EVENT,		CMD_CM_ROLEBASE + 45,	触发实体事件)

	// 二次密码协议
	MESSAGE_DEF(	CMD_CM_CREATE_PASSWORD2,	CMD_CM_ROLEBASE + 46,	创建二次密码)
	MESSAGE_DEF(	CMD_CM_UPDATE_PASSWORD2,	CMD_CM_ROLEBASE + 47,	更新二次密码)

    //读书
    MESSAGE_DEF(	CMD_CM_READBOOK_START,		CMD_CM_ROLEBASE + 48,	开始读书)
	MESSAGE_DEF(	CMD_CM_READBOOK_CLOSE,		CMD_CM_ROLEBASE + 49,	结束读书)

	MESSAGE_DEF(	CMD_CM_SELECT_TIME_ASK,		CMD_CM_ROLEBASE + 50,	选择的离线时间)
	MESSAGE_DEF(	CMD_CM_BEHINDGENIUS_ASK,	CMD_CM_ROLEBASE + 51,	请求制造背后灵)
	MESSAGE_DEF(	CMD_CM_GET_OUTTIMEEXP,		CMD_CM_ROLEBASE + 52,	无)
	MESSAGE_DEF(	CMD_CM_SELECT_COIN_ASK,		CMD_CM_ROLEBASE + 53,	无)
	MESSAGE_DEF(	CMD_CM_REQUEST_ANYTIMETRADE,CMD_CM_ROLEBASE + 54,	随时交易)
	MESSAGE_DEF(	CMD_CM_REQUEST_JEWELRYUP_ASK,CMD_CM_ROLEBASE + 55,	宝石升级)

	//水晶交易平台 Add by sunny.sun 20090409 
	MESSAGE_DEF(	CMD_CM_OPEN_CRYSTALTRADE_ASK,CMD_CM_ROLEBASE + 56,	打开水晶交易平台)
	MESSAGE_DEF(	CMD_CM_REQUEST_BUY_ASK,		CMD_CM_ROLEBASE + 57,	买入挂单)
	MESSAGE_DEF(	CMD_CM_REQUEST_SALE_ASK,	CMD_CM_ROLEBASE + 58,	卖出挂单)
	MESSAGE_DEF(	CMD_CM_REQUEST_CANCEL_ASK,	CMD_CM_ROLEBASE + 59,	取消挂单)
	MESSAGE_DEF(	CMD_CM_REQUEST_GETFLATMONEY,CMD_CM_ROLEBASE + 60,	取出平台账号上的钱)
	MESSAGE_DEF(	CMD_CM_REQUEST_REFRESH_ASK,	CMD_CM_ROLEBASE + 61,	请求刷新)
	MESSAGE_DEF(	CMD_CM_CHA_CONFIRM_CRYSTALTRADE,CMD_CM_ROLEBASE + 62,	玩家确认交易信息)
//End 任务系统指令

//Begin乱斗白银城排名系统
MESSAGE_DEF(	CMD_CM_GARNER2_REORDER,			CMD_CM_ROLEBASE + 71,	客户端请求重排名)
//End乱斗白银城排名系统


MESSAGE_DEF(	CMD_CM_ANTIINDULGENCE,			CMD_CM_ROLEBASE + 72,	防沉迷破解)
//Add by sunny.sun20090728
MESSAGE_DEF(	XTRAP_CMD_STEP_TWO,				CMD_CM_ROLEBASE + 73,	无)
MESSAGE_DEF(	XTRAP_MAP_FILE_CHANGE,			CMD_CM_ROLEBASE + 74,	无)
MESSAGE_DEF(	CMD_CM_OPEN_CYCELMISSION,		CMD_CM_ROLEBASE + 75,	公会循环任务)//Add by sunny.sun 20090831

/*=====================================================================================================
*		Ga(m)eServer -> (C)lient
*/
MESSAGE_DEF(	CMD_MC_ROLEBASE,				CMD_MC_BASE	+ 300,	(300-400)任务系统命令基址)
MESSAGE_DEF(	CMD_MC_GULDBASE,				CMD_MC_BASE	+ 400,	(400-430)公会命令基址)
MESSAGE_DEF(	CMD_MC_CHARBASE,				CMD_MC_BASE	+ 430,	(430-450)角色命令基址)

MESSAGE_DEF(	CMD_MC_SAY,						CMD_MC_BASE + 1,	视野内说话)
MESSAGE_DEF(	CMD_MC_MAPCRASH,				CMD_MC_BASE	+ 3,	无)
MESSAGE_DEF(	CMD_MC_CHABEGINSEE,				CMD_MC_BASE + 4,	无)
MESSAGE_DEF(	CMD_MC_CHAENDSEE,				CMD_MC_BASE + 5,	无)
MESSAGE_DEF(	CMD_MC_ITEMBEGINSEE,			CMD_MC_BASE + 6,	无)
MESSAGE_DEF(	CMD_MC_ITEMENDSEE,				CMD_MC_BASE + 7,	无)

MESSAGE_DEF(	CMD_MC_NOTIACTION,				CMD_MC_BASE + 8,	无)
	//long	角色ID
	//char	行动类型（1，移动；2，使用技能；3，技能影响）
	//	类型1：移动
	//		char	状态（0x00，移动中。0x01，到达目标点停止。0x02遇到障碍停止。0x04，客户端要求停止。0x08，到达要求的范围(如攻击范围)停止。）
	//		Point	点序列（包含player的当前位置）
	//	类型2：使用技能
	//		char	状态（0x00，使用中。0x01，对象死亡而停止。0x02，对象离开使用范围而停止。0x04，达到了使用目的而停止（单击）。0x08，客户要求停止。）
	//		long	技能编号（0，物理攻击；其他，技能ID）
	//		技能参数，根据技能的类型（个体，范围）选择下列参数
	//		long	目标ID
	//		Point	目标位置
	//	类型3：技能影响
	//		long	使用方的角色ID
	//		long	使用的技能ID
	//		结果序列
	//		long	影响的属性ID
	//		long	影响的数值
	//	类型4：换装
MESSAGE_DEF(	CMD_MC_SYNATTR,					CMD_MC_BASE + 9,	同步角色属性（同步属性的最终值）)
MESSAGE_DEF(	CMD_MC_SYNSKILLBAG,				CMD_MC_BASE + 10,	同步技能栏)
MESSAGE_DEF(	CMD_MC_SYNASKILLSTATE,			CMD_MC_BASE + 11,	同步角色状态)
MESSAGE_DEF(	CMD_MC_PING,					CMD_MC_BASE + 15,	无)
MESSAGE_DEF(	CMD_MC_ENTERMAP,				CMD_MC_BASE	+ 16,	GameServer通知Client进入地图，附带玩家的所有信息及其附属结构)
MESSAGE_DEF(	CMD_MC_SYSINFO,					CMD_MC_BASE	+ 17,	系统消息提示命令，如玩家不在线，你还没有完成什么任务等等。)
MESSAGE_DEF(	CMD_MC_ALARM,					CMD_MC_BASE	+ 18,	无)
MESSAGE_DEF(	CMD_MC_TEAM,					CMD_MC_BASE + 19,	GameServer通知客户端某个队员的属性刷新(比如外观, HP,SP))
MESSAGE_DEF(	CMD_MC_FAILEDACTION,			CMD_MC_BASE + 20,	请求的行动执行失败)
MESSAGE_DEF(	CMD_MC_MESSAGE,					CMD_MC_BASE + 21,	提示信息)
MESSAGE_DEF(	CMD_MC_ASTATEBEGINSEE,			CMD_MC_BASE + 22,	地面状态)
MESSAGE_DEF(	CMD_MC_ASTATEENDSEE,			CMD_MC_BASE + 23,	无)
MESSAGE_DEF(	CMD_MC_TLEADER_ID,				CMD_MC_BASE + 24,	GameServer通知客户端某个队员的队长信息)
MESSAGE_DEF(	CMD_MC_CHA_EMOTION,				CMD_MC_BASE + 25,	GameServer触发指定角色做表情   )

MESSAGE_DEF(	CMD_MC_QUERY_CHA,				CMD_MC_BASE + 26,	查询角色基本信息)
MESSAGE_DEF(	CMD_MC_QUERY_CHAITEM,			CMD_MC_BASE + 27,	查询角色道具)
MESSAGE_DEF(	CMD_MC_CALL_CHA,				CMD_MC_BASE + 28,	将角色召唤到自己身边)
MESSAGE_DEF(	CMD_MC_GOTO_CHA,				CMD_MC_BASE + 29,	将自己传送到角色身边)
MESSAGE_DEF(	CMD_MC_KICK_CHA,				CMD_MC_BASE + 30,	将角色踢下线)
MESSAGE_DEF(	CMD_MC_SYNDEFAULTSKILL,			CMD_MC_BASE + 31,	同步默认技能)
MESSAGE_DEF(	CMD_MC_ADD_ITEM_CHA,			CMD_MC_BASE + 32,	添加道具角色)
MESSAGE_DEF(	CMD_MC_DEL_ITEM_CHA,			CMD_MC_BASE + 33,	删除道具角色)
MESSAGE_DEF(	CMD_MC_QUERY_CHAPING,			CMD_MC_BASE + 34,	查询角色到GameServer逻辑层的ping值)
MESSAGE_DEF(	CMD_MC_QUERY_RELIVE,			CMD_MC_BASE + 35,	咨询是否接受原地复活)
MESSAGE_DEF(	CMD_MC_PREMOVE_TIME,			CMD_MC_BASE + 36,	预移动时间)
MESSAGE_DEF(	CMD_MC_CHECK_PING,				CMD_MC_BASE + 37,	计算Ping)
MESSAGE_DEF(	CMD_MC_MAP_MASK,				CMD_MC_BASE + 38,	无)

MESSAGE_DEF(	CMD_MC_OPENHAIR,				CMD_MC_BASE + 39,	打开理发界面)
MESSAGE_DEF(	CMD_MC_UPDATEHAIR_RES,			CMD_MC_BASE + 40,	更换发型的结果)
MESSAGE_DEF(	CMD_MC_EVENT_INFO,				CMD_MC_BASE + 41,	同步事件信息)
MESSAGE_DEF(	CMD_MC_SIDE_INFO,				CMD_MC_BASE + 42,	同步分边信息)
MESSAGE_DEF(	CMD_MC_TEAM_FIGHT_ASK,			CMD_MC_BASE + 43,	队伍挑战请求)
MESSAGE_DEF(	CMD_MC_ITEM_REPAIR_ASK,			CMD_MC_BASE + 44,	道具修理请求)
MESSAGE_DEF(	CMD_MC_ITEM_REPAIR_ASR,			CMD_MC_BASE + 45,	道具修理应答)
MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_REPAIR,		CMD_MC_BASE + 46,	开始道具修理)
MESSAGE_DEF(	CMD_MC_APPEND_LOOK,				CMD_MC_BASE + 47,	附加外观)
MESSAGE_DEF(	CMD_MC_ITEM_FORGE_ASK,			CMD_MC_BASE + 48,	道具精炼请求)
MESSAGE_DEF(	CMD_MC_ITEM_FORGE_ASR,			CMD_MC_BASE + 49,	道具精炼应答)
MESSAGE_DEF(	CMD_MC_ITEM_USE_SUC,			CMD_MC_BASE + 50,	道具使用成功)


MESSAGE_DEF(	CMD_MC_KITBAG_CAPACITY,			CMD_MC_BASE + 51,	背包容量)
MESSAGE_DEF(	CMD_MC_ESPE_ITEM,				CMD_MC_BASE + 52,	特殊道具)

//背包锁定
MESSAGE_DEF(	CMD_MC_KITBAG_CHECK_ASR,		CMD_MC_BASE + 53,	背包锁定状态的应答)
MESSAGE_DEF(	CMD_MC_KITBAGTEMP_SYNC,			CMD_MC_BASE + 54,	同步临时背包)

//商城系统
MESSAGE_DEF(	CMD_MC_STORE_OPEN_ASR,			CMD_MC_BASE + 61,	打开商城)
MESSAGE_DEF(	CMD_MC_STORE_LIST_ASR,			CMD_MC_BASE + 62,	商城列表)
MESSAGE_DEF(	CMD_MC_STORE_BUY_ASR,			CMD_MC_BASE + 63,	购买道具)
MESSAGE_DEF(	CMD_MC_STORE_CHANGE_ASR,		CMD_MC_BASE + 64,	兑换代币)
MESSAGE_DEF(	CMD_MC_STORE_QUERY,				CMD_MC_BASE + 65,	交易记录查询)
MESSAGE_DEF(	CMD_MC_STORE_VIP,				CMD_MC_BASE + 66,	VIP)
MESSAGE_DEF(	CMD_MC_STORE_AFFICHE,			CMD_MC_BASE + 67,	公告商品)
MESSAGE_DEF(	CMD_MC_POPUP_NOTICE,			CMD_MC_BASE + 68,	无)

//黑市交易
MESSAGE_DEF(	CMD_MC_BLACKMARKET_EXCHANGEDATA,	CMD_MC_BASE + 71,	黑市兑换数据)
MESSAGE_DEF(	CMD_MC_BLACKMARKET_EXCHANGE_ASR,	CMD_MC_BASE + 72,	黑市兑换应答)
MESSAGE_DEF(	CMD_MC_BLACKMARKET_EXCHANGEUPDATE,	CMD_MC_BASE + 73,	黑市兑换更新)
MESSAGE_DEF(	CMD_MC_BLACKMARKET_TRADEUPDATE,	CMD_MC_BASE + 74,	黑市交易更新)
MESSAGE_DEF(	CMD_MC_EXCHANGEDATA,			CMD_MC_BASE + 75,	普通兑换数据)

//老手带新手
MESSAGE_DEF(	CMD_MC_VOLUNTER_LIST,			CMD_MC_BASE + 81,	显示志愿者列表)
MESSAGE_DEF(	CMD_MC_VOLUNTER_STATE,			CMD_MC_BASE + 82,	志愿者状态)
MESSAGE_DEF(	CMD_MC_VOLUNTER_SEL,			CMD_MC_BASE + 83,	申请组队)
MESSAGE_DEF(	CMD_MC_VOLUNTER_OPEN,			CMD_MC_BASE + 84,	打开志愿者面板)
MESSAGE_DEF(	CMD_MC_VOLUNTER_ASK,			CMD_MC_BASE + 85,	志愿者组队申请)

MESSAGE_DEF(	CMD_MC_LISTAUCTION,				CMD_MC_BASE + 86,	无)

//拜师
MESSAGE_DEF(	CMD_MC_MASTER_ASK,				CMD_MC_BASE + 91,	无)
MESSAGE_DEF(	CMD_MC_PRENTICE_ASK,			CMD_MC_BASE + 92,	无)
MESSAGE_DEF(	CMD_MC_CHAPLAYEFFECT,			CMD_MC_BASE + 93,	无)

MESSAGE_DEF(	CMD_MC_SAY2CAMP,				CMD_MC_BASE + 96,	无)
MESSAGE_DEF(	CMD_MC_GM_MAIL,					CMD_MC_BASE + 97,	无)
MESSAGE_DEF(	CMD_MC_CHEAT_CHECK,				CMD_MC_BASE + 98,	无)

//	2008-8-29	yangyinyu	add	begin!
MESSAGE_DEF(	CMD_CM_ITEM_LOCK_ASR,			CMD_MC_BASE	+	99,	无)
//	2008-8-29	yangyinyu	add	end!

MESSAGE_DEF(	CMD_MC_ITEM_UNLOCK_ASR,			CMD_MC_BASE	+	95,	无)

// FEATURE: GUILD_BANK
MESSAGE_DEF(CMD_MC_UPDATEGUILDBANKGOLD, CMD_MC_BASE + 120, Update Guild Bank Gold)

//Begin 公会命令定义
	MESSAGE_DEF(	CMD_MC_GUILD_GETNAME,		CMD_MC_GULDBASE	+ 1,	请求客户端输入公会名)
	MESSAGE_DEF(	CMD_MC_LISTGUILD,			CMD_MC_GULDBASE	+ 2,	命令客户端打开申请加入窗口并加入行会列表)
	MESSAGE_DEF(	CMD_MC_GUILD_TRYFORCFM,		CMD_MC_GULDBASE	+ 3,	确认是否覆盖以前申请)
	MESSAGE_DEF(	CMD_MC_GUILD_LISTTRYPLAYER,	CMD_MC_GULDBASE	+ 4,	列出所有待批复玩家)
	MESSAGE_DEF(	CMD_MC_GUILD_LISTCHALL,		CMD_MC_GULDBASE + 5,	查询公会挑战信息)
	MESSAGE_DEF(	CMD_MC_GUILD_MOTTO,			CMD_MC_GULDBASE	+ 10,	修改座右铭)
	MESSAGE_DEF(	CMD_MC_GUILD_LEAVE,			CMD_MC_GULDBASE + 11,	离开公会)
	MESSAGE_DEF(	CMD_MC_GUILD_KICK,			CMD_MC_GULDBASE + 12,	被踢出公会)
	MESSAGE_DEF(	CMD_MC_GUILD_INFO,			CMD_MC_GULDBASE + 13,	同步公会信息)
//End 公会命令定义

//Begin 角色操作和登录命令CMD_MC_CHARBASE
	MESSAGE_DEF(	CMD_MC_LOGIN,				CMD_MC_CHARBASE + 1,	无)
	MESSAGE_DEF(	CMD_MC_LOGOUT,				CMD_MC_CHARBASE + 2,	无)
	MESSAGE_DEF(	CMD_MC_BGNPLAY,				CMD_MC_CHARBASE + 3,	无)
	MESSAGE_DEF(	CMD_MC_ENDPLAY,				CMD_MC_CHARBASE + 4,	无)
	MESSAGE_DEF(	CMD_MC_NEWCHA,				CMD_MC_CHARBASE	+ 5,	无)
	MESSAGE_DEF(	CMD_MC_DELCHA,				CMD_MC_CHARBASE	+ 6,	无)
	MESSAGE_DEF(	CMD_MC_STARTEXIT,			CMD_MC_CHARBASE + 7	,	开始退出倒计时)
	MESSAGE_DEF(	CMD_MC_CANCELEXIT,			CMD_MC_CHARBASE + 8	,	取消退出倒计时)
	MESSAGE_DEF(	CMD_MC_CHAPSTR,				CMD_MC_CHARBASE	+ 10,	无)
	MESSAGE_DEF(	CMD_MC_CREATE_PASSWORD2,	CMD_MC_CHARBASE + 11,	无)
	MESSAGE_DEF(	CMD_MC_UPDATE_PASSWORD2,	CMD_MC_CHARBASE + 12,	无)
	MESSAGE_DEF(    CMD_MC_SYNCCHAR, CMD_MC_CHARBASE + 13, 无)
	MESSAGE_DEF(CMD_MC_GETORIGCOLOR, CMD_MC_CHARBASE + 14, GetOrigColor)
	MESSAGE_DEF(	CMD_MC_CHANGETITLE, CMD_MC_CHARBASE + 15, Changetitle)
	MESSAGE_DEF(CMD_MC_SYNGUILDCOLOR, CMD_MC_CHARBASE + 16, SynGuildColor)

//End 角色操作和登录命令

//Begin 任务系统指令
	MESSAGE_DEF(	CMD_MC_TALKPAGE,			CMD_MC_ROLEBASE + 1,	服务器向客户端发送对话信息)
	MESSAGE_DEF(	CMD_MC_FUNCPAGE,			CMD_MC_ROLEBASE + 2,	服务器向客户端发送功能选项页信息)
	MESSAGE_DEF(	CMD_MC_CLOSETALK,			CMD_MC_ROLEBASE + 3,	服务器向客户端发送关闭对话信息)
	MESSAGE_DEF(	CMD_MC_HELPINFO,			CMD_MC_ROLEBASE + 4,	服务器向客户端发送帮助信息)
	MESSAGE_DEF(	CMD_MC_TRADEPAGE,			CMD_MC_ROLEBASE + 5,	服务器向客户端发送交易信息)
	MESSAGE_DEF(	CMD_MC_TRADERESULT,			CMD_MC_ROLEBASE + 6,	服务器向客户端发送交易请求答复信息)
	MESSAGE_DEF(	CMD_MC_TRADE_DATA,			CMD_MC_ROLEBASE + 7,	NPC交易数据信息更新)
	MESSAGE_DEF(	CMD_MC_TRADE_ALLDATA,		CMD_MC_ROLEBASE + 8,	NPC交易数据信息更新)
	MESSAGE_DEF(	CMD_MC_TRADE_UPDATE,		CMD_MC_ROLEBASE + 9,	黑市商人交易信息更新)
	MESSAGE_DEF(	CMD_MC_EXCHANGE_UPDATE,		CMD_MC_ROLEBASE + 10,	黑市商人兑换信息更新)

	//角色交易指令
	MESSAGE_DEF(	CMD_MC_CHARTRADE,			CMD_MC_ROLEBASE + 11,	服务器向客户端发送交易信息 )
	MESSAGE_DEF(	CMD_MC_CHARTRADE_REQUEST,	CMD_MC_ROLEBASE + 12,	服务器向客户端发送其他角色邀请交易信息)
	MESSAGE_DEF(	CMD_MC_CHARTRADE_CANCEL,	CMD_MC_ROLEBASE + 13,	服务器向客户端发送 )
	MESSAGE_DEF(	CMD_MC_CHARTRADE_ITEM,		CMD_MC_ROLEBASE + 14,	服务器向客户端角色发送交易的物品信息)
	MESSAGE_DEF(	CMD_MC_CHARTRADE_PAGE,		CMD_MC_ROLEBASE + 15,	服务器向客户端发送开始交易界面信息)
	MESSAGE_DEF(	CMD_MC_CHARTRADE_VALIDATEDATA,	CMD_MC_ROLEBASE + 16,	确认交易数据)
	MESSAGE_DEF(	CMD_MC_CHARTRADE_VALIDATE,	CMD_MC_ROLEBASE + 17,	确认交易)
	MESSAGE_DEF(	CMD_MC_CHARTRADE_RESULT,	CMD_MC_ROLEBASE + 18,	确认交易成功)
	MESSAGE_DEF(	CMD_MC_CHARTRADE_MONEY,		CMD_MC_ROLEBASE + 19,	拖动金钱操作)
	MESSAGE_DEF(	CMD_MC_MISSION,				CMD_MC_ROLEBASE + 22,	服务器向客户端发送任务列表页信息)
	MESSAGE_DEF(	CMD_MC_MISSIONLIST,			CMD_MC_ROLEBASE + 23,	任务列表)
	MESSAGE_DEF(	CMD_MC_MISSIONTALK,			CMD_MC_ROLEBASE + 24,	任务对话)
	MESSAGE_DEF(	CMD_MC_NPCSTATECHG,			CMD_MC_ROLEBASE + 25,	请求切换npc状态)
	MESSAGE_DEF(	CMD_MC_TRIGGER_ACTION,		CMD_MC_ROLEBASE + 26,	触发器动作)
	MESSAGE_DEF(	CMD_MC_MISPAGE,				CMD_MC_ROLEBASE + 27,	任务页信息)
	MESSAGE_DEF(	CMD_MC_MISLOG,				CMD_MC_ROLEBASE + 28,	任务日志)
	MESSAGE_DEF(	CMD_MC_MISLOGINFO,			CMD_MC_ROLEBASE + 29,	单个任务详细信息)
	MESSAGE_DEF(	CMD_MC_MISLOG_CHANGE,		CMD_MC_ROLEBASE + 30,	任务状态变化)
	MESSAGE_DEF(	CMD_MC_MISLOG_CLEAR,		CMD_MC_ROLEBASE + 31,	清除一个任务)
	MESSAGE_DEF(	CMD_MC_MISLOG_ADD,			CMD_MC_ROLEBASE + 32,	添加一个任务)

	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_FUSION,	CMD_MC_ROLEBASE + 33	,	开始熔合道具)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_UPGRADE,	CMD_MC_ROLEBASE + 34	,	开始道具升级)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_FORGE,	CMD_MC_ROLEBASE + 35	,	开始道具精炼)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_UNITE,	CMD_MC_ROLEBASE + 36	,	开始道具合成)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_MILLING,	CMD_MC_ROLEBASE + 37	,	开始道具打磨)

	MESSAGE_DEF(	CMD_MC_CREATEBOAT,			CMD_MC_ROLEBASE + 38,	创建船只)
	MESSAGE_DEF(	CMD_MC_UPDATEBOAT,			CMD_MC_ROLEBASE + 39,	改造船只)
	MESSAGE_DEF(	CMD_MC_UPDATEBOAT_PART,		CMD_MC_ROLEBASE + 40,	改造船只的部件)
	MESSAGE_DEF(	CMD_MC_BERTH_LIST,			CMD_MC_ROLEBASE + 41,	船只停泊列表)
	MESSAGE_DEF(	CMD_MC_BOAT_LIST,			CMD_MC_ROLEBASE + 42,	同步角色拥有的所有船只属性)
	MESSAGE_DEF(	CMD_MC_BOAT_ADD,			CMD_MC_ROLEBASE + 43,	添加一艘船)
	MESSAGE_DEF(	CMD_MC_BOAT_CLEAR,			CMD_MC_ROLEBASE + 44,	清除一艘船)
	MESSAGE_DEF(	CMD_MC_BOATINFO,			CMD_MC_ROLEBASE + 45,	同步船只属性信息)
	MESSAGE_DEF(	CMD_MC_BOAT_BAGLIST,		CMD_MC_ROLEBASE + 46,	显示可以打包的船只列表)

	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_EIDOLON_METEMPSYCHOSIS,	CMD_MC_ROLEBASE + 47,	开始精灵转生)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_EIDOLON_FUSION,	CMD_MC_ROLEBASE + 48,	开始精灵融合)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_PURIFY,	CMD_MC_ROLEBASE + 49	,	开始装备提纯)
	
	// 事件实体交互协议命令
	MESSAGE_DEF(	CMD_MC_ENTITY_BEGINESEE,	CMD_MC_ROLEBASE + 50,	同步视野实体信息)
	MESSAGE_DEF(	CMD_MC_ENTITY_ENDSEE,		CMD_MC_ROLEBASE + 51,	实体信息超出视野)
	MESSAGE_DEF(	CMD_MC_ENTITY_CHGSTATE,		CMD_MC_ROLEBASE + 52,	实体状态改变)

	// 摆摊
	MESSAGE_DEF(	CMD_MC_STALL_ALLDATA,		CMD_MC_ROLEBASE + 54,	查看摆摊所有信息)
	MESSAGE_DEF(	CMD_MC_STALL_UPDATE,		CMD_MC_ROLEBASE + 55,	摆摊货物更新信息)
	MESSAGE_DEF(	CMD_MC_STALL_DELGOODS,		CMD_MC_ROLEBASE + 56,	删除指定位置的货物)
	MESSAGE_DEF(	CMD_MC_STALL_CLOSE,			CMD_MC_ROLEBASE + 57,	摊主收摊)
	MESSAGE_DEF(	CMD_MC_STALL_START,			CMD_MC_ROLEBASE + 58,	成功摆摊)
	MESSAGE_DEF(	CMD_MC_STALL_NAME,			CMD_MC_ROLEBASE + 59,	摆摊名)

	// 闪动字体信息
	MESSAGE_DEF(	CMD_MC_BICKER_NOTICE,		CMD_MC_ROLEBASE + 60,	闪动字体信息通知)

	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_ENERGY,	CMD_MC_ROLEBASE + 71	,	开始贝壳充电)
	MESSAGE_DEF(	CMD_MC_BEGIN_GET_STONE,		CMD_MC_ROLEBASE + 72	,	开始提取宝石)
	MESSAGE_DEF(	CMD_MC_BEGIN_TIGER,			CMD_MC_ROLEBASE + 73	,	精灵老虎机界面)
	MESSAGE_DEF(	CMD_MC_TIGER_ITEM_ID,		CMD_MC_ROLEBASE + 74	,	老虎机道具ID)
	MESSAGE_DEF(	CMD_MC_TIGER_STOP,			CMD_MC_ROLEBASE + 75	,	老虎机结束)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_FIX,		CMD_MC_ROLEBASE + 76	,	修理破锅)
	MESSAGE_DEF(	CMD_MC_BEGIN_GM_SEND,		CMD_MC_ROLEBASE + 77	,	发送GM邮件)
	MESSAGE_DEF(	CMD_MC_BEGIN_GM_RECV,		CMD_MC_ROLEBASE + 78	,	接收GM邮件)

	// Add by lark.li 20080514 begin
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_LOTTERY,	CMD_MC_ROLEBASE + 79	,	开始设置彩票)
	// End
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_AMPHITHEATER,	CMD_MC_ROLEBASE + 80,	打开竞技场排行榜)
	//Add by sunny.sun 20090306 begin
	MESSAGE_DEF(	CMD_MC_LEAVE_TIME_ASR,		CMD_MC_ROLEBASE + 81,	角色离线时间)
	MESSAGE_DEF(	CMD_MC_SELECT_TIME_ASR,		CMD_MC_ROLEBASE + 82,	获取离线经验消息回复)
	MESSAGE_DEF(	CMD_MC_BEHINDGENIUS_ASR,	CMD_MC_ROLEBASE + 83	,	背后灵制造应答)
	MESSAGE_DEF(	CMD_MC_BEGIN_ITEM_JEWELRYUP,CMD_MC_ROLEBASE + 84	,	弹开宝石升级界面)
	//Add by sunny.sun 20090414
	MESSAGE_DEF(	CMD_MC_OPEN_CRYSTALTRADE_ASR,CMD_MC_ROLEBASE + 85	,	打开水晶平台应答)
	MESSAGE_DEF(	CMD_MC_REQUEST_BUY_ASR,		CMD_MC_ROLEBASE + 86 ,	买入挂单应答)
	MESSAGE_DEF(	CMD_MC_REQUEST_SALE_ASR,	CMD_MC_ROLEBASE + 87 ,	卖出挂单应答)
	MESSAGE_DEF(	CMD_MC_REQUEST_CANCEL_ASR,	CMD_MC_ROLEBASE + 88 ,	取消挂单应答)
	MESSAGE_DEF(	CMD_MC_REQUEST_GETFLATMONEY,CMD_MC_ROLEBASE + 89 ,	取出平台上的钱应答)
	MESSAGE_DEF(	CMD_MC_REQUEST_REFRESH_ASR,	CMD_MC_ROLEBASE + 90 ,	请求刷新应答)
	MESSAGE_DEF(	CMD_MC_GET_CRYSTALSTATE,	CMD_MC_ROLEBASE + 91 ,	获取交易状态)
	//End

//生活技能
MESSAGE_DEF(	CMD_MC_LIFESKILL_BGING,			CMD_MC_BASE + 100	,	生活技能开始)
MESSAGE_DEF(	CMD_MC_LIFESKILL_ASR,			CMD_MC_BASE + 101	,	生活技能用运，合成，分解等的请求)
MESSAGE_DEF(	CMD_MC_LIFESKILL_ASK,			CMD_MC_BASE + 102	,	生活技能用运，合成，分解等的确认)

// Add by lark.li 20080515 begin
MESSAGE_DEF(	CMD_MC_ITEM_LOTTERY_ASK,		CMD_MC_BASE + 103,	彩票请求)
MESSAGE_DEF(	CMD_MC_ITEM_LOTTERY_ASR,		CMD_MC_BASE + 104,	彩票应答)
// End

// Add by lark.li 20080707 begin
MESSAGE_DEF(	CMD_MC_CAPTAIN_ASK,				CMD_MC_BASE + 105,	竞技场队长确认请求)
// End

MESSAGE_DEF(	CMD_MC_ITEM_AMPHITHEATER_ASR,	CMD_MC_BASE + 106, 无)
MESSAGE_DEF(	CMD_MC_REQUEST_JEWELRYUP_ASR,	CMD_MC_BASE + 107, 无)

MESSAGE_DEF(	XTRAP_CMD_STEP_ONE,				CMD_MC_BASE + 108, 无)

//End 任务系统指令

/*=====================================================================================================
*					Ga(t)eServer <->Ga(m)eServer
*/
MESSAGE_DEF(	CMD_TM_ENTERMAP,				CMD_TM_BASE	+ 3	,	进地图，附带角色ID、进入地图的名字、位置(x,y))
MESSAGE_DEF(	CMD_TM_GOOUTMAP,				CMD_TM_BASE + 4		,	出地图)
MESSAGE_DEF(	CMD_TM_LOGIN_ACK,				CMD_TM_BASE + 5, 无)
MESSAGE_DEF(	CMD_TM_CHANGE_PERSONINFO,		CMD_TM_BASE	+6	,	修改个人信息)
MESSAGE_DEF(	CMD_TM_MAPENTRY,				CMD_TM_BASE + 7, 无)
MESSAGE_DEF(	CMD_TM_MAPENTRY_NOMAP,			CMD_TM_BASE + 8, 无)
MESSAGE_DEF(	CMD_TM_MAP_ADMIN,				CMD_TM_BASE + 9	,	管理员用地图控制命令)
MESSAGE_DEF(	CMD_TM_STATE,					CMD_TM_BASE + 10,	服务器的状态（运行内存情况，版本）)
//---------------------------------------------------

MESSAGE_DEF(	CMD_MT_LOGIN,					CMD_MT_BASE + 1		,	GameServer登陆GateServer)
MESSAGE_DEF(	CMD_MT_SWITCHMAP,				CMD_MT_BASE + 4		,	开始切换地图命令)
MESSAGE_DEF(	CMD_MT_KICKUSER,				CMD_MT_BASE + 5		,	GameServer踢掉某个用户)
MESSAGE_DEF(	CMD_MT_MAPENTRY,				CMD_MT_BASE + 6		,	地图入口)
MESSAGE_DEF(	CMD_MT_PALYEREXIT,				CMD_MT_BASE + 8		,	通知Gate释放该用户资源)
MESSAGE_DEF(	CMD_MT_MAP_ADMIN,				CMD_MT_BASE + 9	,	管理员用地图控制命令)
MESSAGE_DEF(	CMD_MT_STATE,					CMD_MT_BASE + 10,	服务器的状态（运行内存情况，版本）)

/*=====================================================================================================
*					Grou(p)eServer <->Ga(m)eServer 
*/
MESSAGE_DEF(	CMD_PM_TEAM,					CMD_PM_BASE + 1    ,	GroupServer发来的组队信息更新)
//CMD_PM_TEAM子类型定义Begin
	MESSAGE_DEF(	TEAM_MSG_ADD,				1                  ,	子类型: 增加新队员)
	MESSAGE_DEF(	TEAM_MSG_LEAVE,				2                  ,	子类型: 队员离开)
	MESSAGE_DEF(	TEAM_MSG_UPDATE,			3                  ,	子类型: 刷新队伍 只用服务器间跳转时候刷新到GameServer使用)	
	MESSAGE_DEF(	TEAM_MSG_GROUP_ADD,			4                  ,	成立队伍)
	MESSAGE_DEF(	TEAM_MSG_GROUP_BREAK,		5                  ,	解散队伍)
	MESSAGE_DEF(	TEAM_MSG_KICK,				6				,	踢出队伍某个成员)
MESSAGE_DEF(	CMD_PM_GUILD_DISBAND,			CMD_PM_BASE	+ 2		,	解散公会)
//CMD_PM_TEAM子类型定义End

MESSAGE_DEF(	CMD_PM_GUILDINFO,				CMD_PM_BASE + 4	,	GroupServer发来的公会同步信息)
MESSAGE_DEF(	CMD_PM_GUILD_CHALLMONEY,		CMD_PM_BASE + 5    ,	将公会战投标的钱退给会长)
MESSAGE_DEF(	CMD_PM_GUILD_CHALL_PRIZEMONEY,	CMD_PM_BASE + 6    ,	将公会战战奖励的钱给会长)
//Begin乱斗白银城排名系统
MESSAGE_DEF(	CMD_PM_GARNER2_UPDATE,			CMD_PM_BASE +7, 无)
//End乱斗白银城排名系统
MESSAGE_DEF(	CMD_PM_TEAM_CREATE,				CMD_PM_BASE + 8, 无)
MESSAGE_DEF(	CMD_PM_SAY2ALL,					CMD_PM_BASE + 9, 无)
MESSAGE_DEF(	CMD_PM_SAY2TRADE,				CMD_PM_BASE + 10, 无)
MESSAGE_DEF(	CMD_PM_EXPSCALE,				CMD_PM_BASE + 11       ,	 防沉迷系统  影响玩家经验及掉宝率)
MESSAGE_DEF(	CMD_PM_GUILD_INVITE,			CMD_PM_BASE + 12		,	公会邀请)

// FEATURE: GUILD_BANK
MESSAGE_DEF(CMD_PM_GUILDBANK, CMD_PM_BASE + 13, Guild Bank)

//---------------------------------------------------
MESSAGE_DEF(	CMD_MP_ENTERMAP,				CMD_MP_BASE	+ 1, 无)
MESSAGE_DEF(	CMD_MP_GUILD_APPROVE,			CMD_MP_BASE	+ 2, 无)
MESSAGE_DEF(	CMD_MP_GUILD_CREATE,			CMD_MP_BASE	+ 3, 无)
MESSAGE_DEF(	CMD_MP_GUILD_KICK,				CMD_MP_BASE	+ 4, 无)
MESSAGE_DEF(	CMD_MP_GUILD_LEAVE,				CMD_MP_BASE	+ 5, 无)
MESSAGE_DEF(	CMD_MP_GUILD_DISBAND,			CMD_MP_BASE	+ 6, 无)
MESSAGE_DEF(	CMD_MP_GUILD_MOTTO,				CMD_MP_BASE	+ 10, 无)
MESSAGE_DEF(	CMD_MP_GUILD_CHALLMONEY,		CMD_MP_BASE + 13			,	将投标公会的钱退还会长角色)
MESSAGE_DEF(	CMD_MP_GUILD_CHALL_PRIZEMONEY,	CMD_MP_BASE + 14    ,	将公会战奖励的的钱给会长角色)

//Begin乱斗白银城排名系统
MESSAGE_DEF(	CMD_MP_GARNER2_UPDATE,			CMD_MP_BASE +7, 无)
MESSAGE_DEF(	CMD_MP_GARNER2_CGETORDER,		CMD_MP_BASE+15, 无)
//End乱斗白银城排名系统

MESSAGE_DEF(	CMD_MP_TEAM_CREATE,				CMD_MP_BASE + 16, 无)

MESSAGE_DEF(	CMD_MP_MASTER_CREATE,			CMD_MP_BASE + 17, 无)
MESSAGE_DEF(	CMD_MP_MASTER_DEL,				CMD_MP_BASE + 18, 无)
MESSAGE_DEF(	CMD_MP_MASTER_FINISH,			CMD_MP_BASE + 19, 无)
MESSAGE_DEF(	CMD_MP_SAY2ALL,					CMD_MP_BASE + 20, 无)
MESSAGE_DEF(	CMD_MP_SAY2TRADE,				CMD_MP_BASE + 21, 无)
MESSAGE_DEF(	CMD_MP_GM1SAY1,					CMD_MP_BASE + 22, 无)
MESSAGE_DEF(	CMD_MP_GM1SAY,					CMD_MP_BASE + 23, 无)
MESSAGE_DEF(	CMD_MP_GMBANACCOUNT,			CMD_MP_BASE	+ 24, GM封停刷屏账号)

// FEATURE: GUILD_BANK
MESSAGE_DEF(CMD_MP_GUILDBANK, CMD_MP_BASE + 25, Guild Bank)
MESSAGE_DEF(CMD_MP_GUILDADDEXP, CMD_MP_BASE + 26, Guild Attr)
MESSAGE_DEF(CMD_MP_GUILD_PERM, CMD_MP_BASE + 27, Guild Perm)
MESSAGE_DEF(CMD_MP_GUILDNAMECOLOR, CMD_MP_BASE + 28, Guild Color)
/*=====================================================================================================
*					Ga(t)eServer <->Grou(p)Server 
*/
MESSAGE_DEF(	CMD_TP_LOGIN,					CMD_TP_BASE + 1		,	GateServer到GroupServer进程间登陆)
MESSAGE_DEF(	CMD_TP_LOGOUT,					CMD_TP_BASE + 2		,	GateServer到GroupServer进程间登出)
MESSAGE_DEF(	CMD_TP_USER_LOGIN,				CMD_TP_BASE	+ 3		,	用户登入)
MESSAGE_DEF(	CMD_TP_USER_LOGOUT,				CMD_TP_BASE + 4		,	用户登出)
MESSAGE_DEF(	CMD_TP_BGNPLAY,					CMD_TP_BASE	+ 5		,	用户选择角色开始玩游戏)
MESSAGE_DEF(	CMD_TP_ENDPLAY,					CMD_TP_BASE	+ 6		,	用户结束玩游戏进入选/建/删角色画面)
MESSAGE_DEF(	CMD_TP_NEWCHA,					CMD_TP_BASE	+ 7		,	新建角色)
MESSAGE_DEF(	CMD_TP_DELCHA,					CMD_TP_BASE	+ 8		,	删除角色)
MESSAGE_DEF(	CMD_TP_PLAYEREXIT,				CMD_TP_BASE + 9		,	退出角色释放资源)
MESSAGE_DEF(	CMD_TP_REQPLYLST,				CMD_TP_BASE	+ 10	,	请求本GateServer上的玩家地址列表)
MESSAGE_DEF(	CMD_TP_DISC,					CMD_TP_BASE + 11, 无)
MESSAGE_DEF(	CMD_TP_ESTOPUSER_CHECK,			CMD_TP_BASE + 12, 无)
MESSAGE_DEF(	CMD_TP_CREATE_PASSWORD2,		CMD_TP_BASE + 13,	创建二次密码)
MESSAGE_DEF(	CMD_TP_UPDATE_PASSWORD2,		CMD_TP_BASE + 14,	更新二次密码)

// Add by lark.li 20081119 begin
MESSAGE_DEF(	CMD_TP_SYNC_PLYLST,				CMD_TP_BASE	+ 15	,	发送本GateServer上的玩家地址列表)

// End

//---------------------------------------------------
MESSAGE_DEF(	CMD_PT_KICKUSER,				CMD_PT_BASE	+ 11, 无)
MESSAGE_DEF(	CMD_PT_ESTOPUSER,				CMD_PT_BASE + 12,	禁言角色)
MESSAGE_DEF(	CMD_PT_DEL_ESTOPUSER,			CMD_PT_BASE + 13,	解除禁言)

/*=====================================================================================================
*					Grou(p)Server <-> (A)ccountServer
*/
MESSAGE_DEF(	CMD_PA_LOGIN,					CMD_PA_BASE + 2, 无)
MESSAGE_DEF(	CMD_PA_USER_LOGIN,				CMD_PA_BASE + 4, 无)
MESSAGE_DEF(	CMD_PA_USER_LOGOUT,				CMD_PA_BASE + 5, 无)
MESSAGE_DEF(	CMD_PA_USER_DISABLE,			CMD_PA_BASE + 6, 无)
MESSAGE_DEF(	CMD_PA_USER_LOGIN1,				CMD_PA_BASE + 13, 无)
MESSAGE_DEF(	CMD_PA_USER_LOGIN2,				CMD_PA_BASE + 14, 无)
MESSAGE_DEF(	CMD_PA_USER_BILLBGN,			CMD_PA_BASE + 20, 无)
MESSAGE_DEF(	CMD_PA_USER_BILLEND,			CMD_PA_BASE + 21, 无)
MESSAGE_DEF(	CMD_PA_GROUP_BILLEND_AND_LOGOUT,CMD_PA_BASE + 22, 无)
MESSAGE_DEF(	CMD_PA_LOGOUT,					CMD_PA_BASE + 23, 无)
MESSAGE_DEF(	CMD_PA_GMBANACCOUNT,			CMD_PA_BASE + 24, GM封停账号)//Add by sunny.sun 20090828
//---------------------------------------------------
MESSAGE_DEF(	CMD_AP_LOGIN,					CMD_AP_BASE + 2, 无)
MESSAGE_DEF(	CMD_AP_USER_LOGIN,				CMD_AP_BASE + 3, 无)
MESSAGE_DEF(	CMD_AP_RELOGIN,					CMD_AP_BASE + 4, 无)
MESSAGE_DEF(	CMD_AP_KICKUSER,				CMD_AP_BASE	+ 11, 无)
MESSAGE_DEF(	CMD_AP_USER_LOGIN1,				CMD_AP_BASE + 12, 无)
MESSAGE_DEF(	CMD_AP_USER_LOGIN2,				CMD_AP_BASE + 13, 无)
MESSAGE_DEF(	CMD_AP_EXPSCALE,				CMD_AP_BASE + 14, 防沉迷)
/*=====================================================================================================
*					Ga(m)eServer <-> Ga(m)eServer
*
*/
MESSAGE_DEF(	CMD_MM_GATE_RELEASE,			CMD_MM_BASE + 1, 无)
MESSAGE_DEF(	CMD_MM_GATE_CONNECT,			CMD_MM_BASE + 2, 无)
MESSAGE_DEF(	CMD_MM_QUERY_CHA,				CMD_MM_BASE + 3	,	查询角色基本信息)
MESSAGE_DEF(	CMD_MM_QUERY_CHAITEM,			CMD_MM_BASE + 4	,	查询角色道具信息)
MESSAGE_DEF(	CMD_MM_CALL_CHA,				CMD_MM_BASE + 5	,	将角色召唤到自己身边)
MESSAGE_DEF(	CMD_MM_GOTO_CHA,				CMD_MM_BASE + 6	,	将自己传送到角色身边)
MESSAGE_DEF(	CMD_MM_KICK_CHA,				CMD_MM_BASE + 7	,	将角色踢下线)
MESSAGE_DEF(	CMD_MM_GUILD_REJECT,			CMD_MM_BASE + 8	,	拒绝加入公会申请通知命令)
MESSAGE_DEF(	CMD_MM_GUILD_APPROVE,			CMD_MM_BASE + 9	,	拒绝加入公会申请通知命令)
MESSAGE_DEF(	CMD_MM_GUILD_KICK,				CMD_MM_BASE	+ 10,	从公会里面剔除某人)
MESSAGE_DEF(	CMD_MM_GUILD_DISBAND,			CMD_MM_BASE	+ 11,	解散公会)
MESSAGE_DEF(	CMD_MM_QUERY_CHAPING,			CMD_MM_BASE + 12,	查询角色到GameServer逻辑层的ping值)
MESSAGE_DEF(	CMD_MM_NOTICE,					CMD_MM_BASE + 13,	系统通告)
MESSAGE_DEF(	CMD_MM_GUILD_MOTTO,				CMD_MM_BASE + 14,	更新公会座佑名)
MESSAGE_DEF(	CMD_MM_DO_STRING,				CMD_MM_BASE + 15,	执行脚本)
MESSAGE_DEF(	CMD_MM_CHA_NOTICE,				CMD_MM_BASE + 16,	对指定玩家的系统通告)
MESSAGE_DEF(	CMD_MM_LOGIN,					CMD_MM_BASE + 17,	玩家登陆游戏)
MESSAGE_DEF(	CMD_MM_GUILD_CHALL_PRIZEMONEY,	CMD_MM_BASE + 18,	退还工会战的费用)
MESSAGE_DEF(	CMD_MM_ADDCREDIT,				CMD_MM_BASE + 19,	增加声望)
MESSAGE_DEF(	CMD_MM_STORE_BUY,				CMD_MM_BASE + 20,	购买商城商品)
MESSAGE_DEF(	CMD_MM_ADDMONEY,				CMD_MM_BASE + 21, 无)
MESSAGE_DEF(	CMD_MM_AUCTION,					CMD_MM_BASE + 22, 无)
MESSAGE_DEF(	CMD_MM_NOTICETOCHA,				CMD_MM_BASE + 23,	水晶交易通知不在同一服务器的交易者)
MESSAGE_DEF(	CMD_MM_EXCHEXTERNVALUE,			CMD_MM_BASE + 24,	脚本改变全局变量)
MESSAGE_DEF(	CMD_MM_NOTICETRADER,			CMD_MM_BASE + 25,	通知交易者)

// FEATURE: GUILD_BANK
MESSAGE_DEF(CMD_MM_UPDATEGUILDBANK, CMD_MM_BASE + 26, Update Guild Bank)
MESSAGE_DEF(CMD_MM_UPDATEGUILDBANKGOLD, CMD_MM_BASE + 27, Update Guild Bank Gold)

/*=====================================================================================================
*					Grou(p)Server <-> (C)lient
*/
//组队命令定义BEGIN
	MESSAGE_DEF(	CMD_CP_TEAM_INVITE,			CMD_CP_BASE	+ 1		,	邀请组队)
	MESSAGE_DEF(	CMD_CP_TEAM_ACCEPT,			CMD_CP_BASE	+ 2		,	确认组队)
	MESSAGE_DEF(	CMD_CP_TEAM_REFUSE,			CMD_CP_BASE	+ 3		,	拒绝组队)
	MESSAGE_DEF(	CMD_CP_TEAM_LEAVE,			CMD_CP_BASE	+ 4		,	离开组队)
	MESSAGE_DEF(	CMD_CP_TEAM_KICK,			CMD_CP_BASE + 5		,	踢出组队)
//组队命令定义END
//好友命令定义BEGIN
	MESSAGE_DEF(	CMD_CP_FRND_INVITE,			CMD_CP_BASE	+ 11	,	好友邀请)
	MESSAGE_DEF(	CMD_CP_FRND_ACCEPT,			CMD_CP_BASE	+ 12	,	好友接收)
	MESSAGE_DEF(	CMD_CP_FRND_REFUSE,			CMD_CP_BASE	+ 13	,	好友拒绝)
	MESSAGE_DEF(	CMD_CP_FRND_DELETE,			CMD_CP_BASE	+ 14	,	好友删除)
	MESSAGE_DEF(	CMD_CP_FRND_MOVE_GROUP,		CMD_CP_BASE	+ 15	,	改变好友所属分组)
	MESSAGE_DEF(	CMD_CP_FRND_REFRESH_INFO,	CMD_CP_BASE	+ 16	,	在自己的客户端刷新别人（好友、队友、同门、路人、陌生人）的个人信息)
	MESSAGE_DEF(	CMD_CP_CHANGE_PERSONINFO,	CMD_CP_BASE	+ 17	,	改变玩家自己的头像等个人信息)

// Add by lark.li 20080804 begin
	MESSAGE_DEF(	CMD_CP_FRND_DEL_GROUP,		CMD_CP_BASE	+ 18, 无)
	MESSAGE_DEF(	CMD_CP_FRND_ADD_GROUP,		CMD_CP_BASE	+ 19, 无)
	MESSAGE_DEF(	CMD_CP_FRND_CHANGE_GROUP,	CMD_CP_BASE	+ 20, 无)
// End

// Add by lark.li 20080808 begin
	MESSAGE_DEF(	CMD_CP_QUERY_PERSONINFO,	CMD_CP_BASE	+ 21, 无)
// End

//好友命令定义END

// Modify by lark.li 20080806 begin
//MESSAGE_DEF(	CMD_CP_PING				CMD_CP_BASE	+ 20
MESSAGE_DEF(	CMD_CP_PING,					CMD_CP_BASE	+ 25, 无)

// 外挂
//MESSAGE_DEF(	CMD_CP_REPORT_WG		CMD_CP_BASE + 21,	报告发现使用外挂
MESSAGE_DEF(	CMD_CP_REPORT_WG,				CMD_CP_BASE + 26,	报告发现使用外挂)
// End

//拜师命令定义BEGIN
MESSAGE_DEF(	CMD_CP_MASTER_REFRESH_INFO,		CMD_CP_BASE	+ 31	,	在自己的客户端刷新师父的个人信息)
MESSAGE_DEF(	CMD_CP_PRENTICE_REFRESH_INFO,	CMD_CP_BASE	+ 32	,	在自己的客户端刷新徒弟的个人信息)
//拜师命令定义END

//Add by sunny.sun 20090605 for Guild Invite 
MESSAGE_DEF(	CMD_CP_GUILD_INVITE,			CMD_CP_BASE + 33, 无)
MESSAGE_DEF(	CMD_CP_GUILD_ACCEPT,			CMD_CP_BASE + 34, 无)
MESSAGE_DEF(	CMD_CP_GUILD_REFUSE,			CMD_CP_BASE + 35, 无)


//公会命令定义Begin

//公会命令定义End
//Begin 聊天指令
	MESSAGE_DEF(	CMD_CP_GM1SAY,				CMD_CP_BASE	+ 400		,	GM的全服广播)
	MESSAGE_DEF(	CMD_CP_SAY2TRADE,			CMD_CP_BASE	+ 401		,	交易频道)
	MESSAGE_DEF(	CMD_CP_SAY2ALL,				CMD_CP_BASE + 402		,	整个游戏世界广播)
	MESSAGE_DEF(	CMD_CP_SAY2YOU,				CMD_CP_BASE	+ 403		,	P2P聊天(玩家对玩家))
	MESSAGE_DEF(	CMD_CP_SAY2TEM,				CMD_CP_BASE	+ 404		,	组队聊天)
	MESSAGE_DEF(	CMD_CP_SAY2GUD,				CMD_CP_BASE	+ 405		,	行会(Guild)聊天)

	MESSAGE_DEF(	CMD_CP_SESS_CREATE,			CMD_CP_BASE	+ 406		,	会话建立)
	MESSAGE_DEF(	CMD_CP_SESS_SAY,			CMD_CP_BASE	+ 407		,	会话说话)
	MESSAGE_DEF(	CMD_CP_SESS_ADD,			CMD_CP_BASE	+ 408		,	会话添加人员)
	MESSAGE_DEF(	CMD_CP_SESS_LEAVE,			CMD_CP_BASE	+ 409		,	离开会话)
	MESSAGE_DEF(	CMD_CP_REFUSETOME,			CMD_CP_BASE	+ 410		,	打开接收私聊开关)
	MESSAGE_DEF(	CMD_CP_GM1SAY1,				CMD_CP_BASE	+ 411		,	滚动广播)
	MESSAGE_DEF(	CMD_CP_GMSAY,				CMD_CP_BASE	+ 412		,	特殊命令执行)

	// FEATURE: GUILD_BANK
	MESSAGE_DEF(CMD_CP_GUILDBANK, CMD_CP_BASE + 414, Guild Bank)

	// GUILD_ATTR
	MESSAGE_DEF(CMD_CP_GUILDATTR, CMD_CP_BASE + 416, Guild Attr)
	MESSAGE_DEF(CMD_CP_GUILDNAMECOLOR, CMD_CP_BASE + 417, Guild Color)
//End 聊天指令
//Begin乱斗白银城排名系统
//End乱斗白银城排名系统
//---------------------------------------------------
//组队命令定义BEGIN
	MESSAGE_DEF(	CMD_PC_TEAM_INVITE,			CMD_PC_BASE	+ 1			,	通知客户端有人邀请组队)
	MESSAGE_DEF(	CMD_PC_TEAM_REFRESH,		CMD_PC_BASE	+ 2			,	通知客户端组队变化的信息，使用CMD_PM_TEAM定义的子类型)
	MESSAGE_DEF(	CMD_PC_TEAM_CANCEL,			CMD_PC_BASE	+ 3			,	服务器因为超时或成员数已满等原因通知被邀请方取消本次邀请)
	//CMD_PC_TEAM_CANCEL子类型定义Begin
		MESSAGE_DEF(	MSG_TEAM_CANCLE_BUSY,	1	,	自己的邀请队列繁忙)
		MESSAGE_DEF(	MSG_TEAM_CANCLE_TIMEOUT,2	,	本次邀请超时)
		MESSAGE_DEF(	MSG_TEAM_CANCLE_OFFLINE,3	,	邀请方已下线)
		MESSAGE_DEF(	MSG_TEAM_CANCLE_ISFULL,	4	,	邀请方的组成员数已满)
		MESSAGE_DEF(	MSG_TEAM_CANCLE_CANCEL,	5	,	被邀请方加入别的/创建了组队或邀请方加入了别人创建的组队而取消了本次邀请)
	//CMD_PC_TEAM_CANCEL子类型定义End
//组队命令定义END
//好友命令定义BEGIN
	MESSAGE_DEF(	CMD_PC_FRND_INVITE,			CMD_PC_BASE	+ 11, 无)
	MESSAGE_DEF(	CMD_PC_FRND_REFRESH,		CMD_PC_BASE	+ 12, 无)
	//CMD_PC_FRND_REFRESH子类型定义Begin
		MESSAGE_DEF(	MSG_FRND_REFRESH_START,	1  ,	子类型: 刚上线时候传输的好友列表)
		MESSAGE_DEF(	MSG_FRND_REFRESH_ADD,	2  ,	子类型: 好友增加)
		MESSAGE_DEF(	MSG_FRND_REFRESH_DEL,	3  ,	子类型: 好友删除)
		MESSAGE_DEF(	MSG_FRND_REFRESH_ONLINE,4,	子类型: 好友上线)
		MESSAGE_DEF(	MSG_FRND_REFRESH_OFFLINE,5  ,	子类型: 好友离线)
	//CMD_PC_FRND_REFRESH子类型定义End
	MESSAGE_DEF(	CMD_PC_FRND_CANCEL,			CMD_PC_BASE	+ 13, 无)
	//CMD_PC_FRND_CANCEL子类型定义Begin
		MESSAGE_DEF(	MSG_FRND_CANCLE_BUSY,	1	,	自己的邀请队列繁忙)
		MESSAGE_DEF(	MSG_FRND_CANCLE_TIMEOUT,2	,	本次邀请超时)
		MESSAGE_DEF(	MSG_FRND_CANCLE_OFFLINE,3	,	邀请方已下线)
		MESSAGE_DEF(	MSG_FRND_CANCLE_INVITER_ISFULL,	4	,	邀请方的好友成员数已满)
		MESSAGE_DEF(	MSG_FRND_CANCLE_SELF_ISFULL,	5	,	自己的好友数已满)
		MESSAGE_DEF(	MSG_FRND_CANCLE_CANCEL,	6	,	邀请方取消了本次邀请)
	//CMD_PC_FRND_CANCEL子类型定义End
	MESSAGE_DEF(	CMD_PC_FRND_MOVE_GROUP,		CMD_PC_BASE + 15	,	改变好友分组成功)
	MESSAGE_DEF(	CMD_PC_FRND_REFRESH_INFO,	CMD_PC_BASE	+ 16	,	刷新好友个人信息)
	MESSAGE_DEF(	CMD_PC_CHANGE_PERSONINFO,	CMD_PC_BASE	+ 17	,	改变玩家自己的头像等个人信息)

// Add by lark.li 20080804 begin
	MESSAGE_DEF(	CMD_PC_FRND_DEL_GROUP,		CMD_PC_BASE + 18	,	删除好友分组成功)
	MESSAGE_DEF(	CMD_PC_FRND_ADD_GROUP,		CMD_PC_BASE + 19	,	新增好友分组成功)
	MESSAGE_DEF(	CMD_PC_FRND_CHANGE_GROUP,	CMD_PC_BASE + 20	,	改变好友分组成功)
// End

// Add by lark.li 20080808 begin
MESSAGE_DEF(	CMD_PC_QUERY_PERSONINFO,		CMD_PC_BASE	+ 21	,	改变玩家自己的头像等个人信息)
// End
	//
//好友命令定义END

// Modify by lark.li 20080806
//MESSAGE_DEF(	CMD_PC_PING				CMD_PC_BASE	+ 20
MESSAGE_DEF(	CMD_PC_PING,					CMD_PC_BASE	+ 25, 无)
// End

//公会命令定义Begin
	MESSAGE_DEF(	CMD_PC_GUILD,				CMD_PC_BASE	+ 30, 无)
	MESSAGE_DEF(	CMD_PC_GUILD_PERM,			CMD_PC_BASE + 31, GuildPerm)
	MESSAGE_DEF(CMD_PC_GUILDNAMECOLOR, CMD_MP_BASE + 32, Guild Color)

	//CMD_PC_GUILD子类型定义Begin
		MESSAGE_DEF(	MSG_GUILD_START,	1, 无)
		MESSAGE_DEF(	MSG_GUILD_ADD,		2, 无)
		MESSAGE_DEF(	MSG_GUILD_DEL,		3, 无)
		MESSAGE_DEF(	MSG_GUILD_ONLINE,	4, 无)
		MESSAGE_DEF(	MSG_GUILD_OFFLINE,	5, 无)
		MESSAGE_DEF(	MSG_GUILD_STOP,		6, 无)
	//CMD_PC_GUILD子类型定义End
//公会命令定义End

	MESSAGE_DEF(	CMD_PC_GUILD_INVITE,		CMD_PC_BASE	+ 31, 无)
	//MESSAGE_DEF(	CMD_PC_GUILD_REFRESH		CMD_PC_BASE	+ 32
//Add by sunny.sun 20090608
MESSAGE_DEF(	CMD_PC_GUILD_CANCEL,		CMD_PC_BASE	+ 33, 无)
	MESSAGE_DEF(	MSG_GUILD_CANCLE_BUSY,			1	,	自己的邀请队列繁忙)
	MESSAGE_DEF(	MSG_GUILD_CANCLE_TIMEOUT,		2	,	本次邀请超时)
	MESSAGE_DEF(	MSG_GUILD_CANCLE_OFFLINE,		3	,	对方已下线)
	MESSAGE_DEF(	MSG_GUILD_CANCLE_SELF_ISFULL,	4	,	对方的公会人员数已满)
	MESSAGE_DEF(	MSG_GUILD_CANCLE_CANCEL,		5	,	对方取消了本次公会邀请)
	MESSAGE_DEF(	MSG_GUILD_CANCLE_SELFCANCEL,	6	,	自己取消了邀请)
//End
//拜师命令定义BEGIN
MESSAGE_DEF(	CMD_PC_MASTER_REFRESH,	CMD_PC_BASE	+ 41, 无)
	//CMD_PC_MASTER_REFRESH子类型定义Begin
	MESSAGE_DEF(	MSG_MASTER_REFRESH_START,		1  ,	子类型: 刚上线时候传输的师父列表)
	MESSAGE_DEF(	MSG_MASTER_REFRESH_ADD,			2  ,	子类型: 师父增加)
	MESSAGE_DEF(	MSG_MASTER_REFRESH_DEL,			3  ,	子类型: 师父删除)
	MESSAGE_DEF(	MSG_MASTER_REFRESH_ONLINE,		4	 ,	子类型: 师父上线)
	MESSAGE_DEF(	MSG_MASTER_REFRESH_OFFLINE,		5  ,	子类型: 师父离线)
	MESSAGE_DEF(	MSG_PRENTICE_REFRESH_START,		6  ,	子类型: 刚上线时候传输的徒弟列表)
	MESSAGE_DEF(	MSG_PRENTICE_REFRESH_ADD,		7  ,	子类型: 徒弟增加)
	MESSAGE_DEF(	MSG_PRENTICE_REFRESH_DEL,		8  ,	子类型: 徒弟删除)
	MESSAGE_DEF(	MSG_PRENTICE_REFRESH_ONLINE,	9  ,	子类型: 徒弟上线)
	MESSAGE_DEF(	MSG_PRENTICE_REFRESH_OFFLINE,	10  ,	子类型: 徒弟离线)
	//CMD_PC_MASTER_REFRESH子类型定义End
MESSAGE_DEF(	CMD_PC_MASTER_CANCEL,	CMD_PC_BASE	+ 42, 无)
	//CMD_PC_MASTER_CANCEL子类型定义Begin
	MESSAGE_DEF(	MSG_MASTER_CANCLE_BUSY,				1	,	自己的拜师队列繁忙)
	MESSAGE_DEF(	MSG_MASTER_CANCLE_TIMEOUT,			2	,	本次拜师超时)
	MESSAGE_DEF(	MSG_MASTER_CANCLE_OFFLINE,			3	,	对方已下线)
	MESSAGE_DEF(	MSG_MASTER_CANCLE_INVITER_ISFULL,	4	,	对方的徒弟数已满)
	MESSAGE_DEF(	MSG_MASTER_CANCLE_SELF_ISFULL,		5	,	自己的师父数已满)
	MESSAGE_DEF(	MSG_MASTER_CANCLE_CANCEL,			6	,	对方取消了本次拜师)
	//CMD_PC_MASTER_CANCEL子类型定义End
MESSAGE_DEF(	CMD_PC_MASTER_REFRESH_INFO,			CMD_PC_BASE	+ 43	,	刷新师父个人信息)
MESSAGE_DEF(	CMD_PC_PRENTICE_REFRESH_INFO,		CMD_PC_BASE	+ 44	,	刷新徒弟个人信息)
//
//拜师命令定义END

//Begin 聊天指令
	MESSAGE_DEF(	CMD_PC_GM1SAY,		CMD_PC_BASE	+ 400		,	GM的全服广播)
	MESSAGE_DEF(	CMD_PC_SAY2TRADE,	CMD_PC_BASE	+ 401		,	交易频道)
	MESSAGE_DEF(	CMD_PC_SAY2ALL,		CMD_PC_BASE + 402		,	整个游戏世界广播)
	MESSAGE_DEF(	CMD_PC_SAY2YOU,		CMD_PC_BASE	+ 403		,	P2P聊天(玩家对玩家))
	MESSAGE_DEF(	CMD_PC_SAY2TEM,		CMD_PC_BASE	+ 404		,	组队聊天)
	MESSAGE_DEF(	CMD_PC_SAY2GUD,		CMD_PC_BASE	+ 405		,	行会(Guild)聊天)

	MESSAGE_DEF(	CMD_PC_SESS_CREATE,	CMD_PC_BASE	+ 406		,	会话建立)
	MESSAGE_DEF(	CMD_PC_SESS_SAY,	CMD_PC_BASE	+ 407		,	会话说话)
	MESSAGE_DEF(	CMD_PC_SESS_ADD,	CMD_PC_BASE	+ 408		,	会话添加人员)
	MESSAGE_DEF(	CMD_PC_SESS_LEAVE,	CMD_PC_BASE	+ 409		,	离开会话)
	MESSAGE_DEF(	CMD_PC_GM1SAY1,	CMD_PC_BASE	+ 411			,	滚动广播)

	// FEATURE: GUILD_BANK
	MESSAGE_DEF(CMD_PC_ERRMSG, CMD_PC_BASE + 414, Error Message)
	MESSAGE_DEF(CMD_PC_UPDATEGUILDATTR, CMD_PC_BASE + 415,	Guild Attr)

//End 聊天指令
//Begin乱斗白银城排名系统
	MESSAGE_DEF(	CMD_PC_GARNER2_ORDER,	CMD_PC_BASE +101, 无)
//End乱斗白银城排名系统

// Add by lark.li 20081119 begin
MESSAGE_DEF(	CMD_OS_LOGIN,		CMD_OS_BASE + 1			,	登录)
MESSAGE_DEF(	CMD_OS_PING,		CMD_OS_BASE + 2			,	检测命令)
MESSAGE_DEF(	CMD_SO_LOGIN,		CMD_SO_BASE + 1			,	登录命令)
MESSAGE_DEF(	CMD_SO_PING,		CMD_SO_BASE + 2			,	检测命令)
MESSAGE_DEF(	CMD_SO_WARING,		CMD_SO_BASE + 3			,	警告命令)
MESSAGE_DEF(	CMD_SO_EXCEPTION,	CMD_SO_BASE + 4		,	异常命令)

MESSAGE_DEF(	CMD_SO_ON_LINE,		CMD_SO_BASE + 5			,	上线命令)
MESSAGE_DEF(	CMD_SO_OFF_LINE,	CMD_SO_BASE + 6			,	下线命令)
MESSAGE_DEF(	CMD_SO_ENTER_MAP,	CMD_SO_BASE + 7			,	进入地图命令)
MESSAGE_DEF(	CMD_SO_LEAVE_MAP,	CMD_SO_BASE + 8			,	离开地图命令)

// End

// Add by lark.li 20090601 begin
MESSAGE_DEF(	CMD_AB_LOGIN,		CMD_AB_BASE + 1			,	登录)
MESSAGE_DEF(	CMD_AB_LOGOUT,		CMD_AB_BASE + 2			,	登出)

MESSAGE_DEF(	CMD_AB_USER_LOGINT,	CMD_AB_BASE + 3			,	玩家登录)
MESSAGE_DEF(	CMD_AB_USER_LOGOUT,	CMD_AB_BASE + 4			,	玩家登出)

MESSAGE_DEF(	CMD_BA_USER_TIME,	CMD_BA_BASE + 1			,	玩家时间通知)
MESSAGE_DEF(	CMD_BA_KILL_USER,	CMD_BA_BASE + 2			,	踢掉玩家（目前两种情况1.上线时玩家已经过了5小时健康时间2.玩家认证失败）)

// End

inline static void InitMessage()
{
	MESSAGE_ADD(	CMD_CM_ROLEBASE,				CMD_CM_BASE + 300,	(300-400)任务系统命令基数)
	MESSAGE_ADD(	CMD_CM_GULDBASE,				CMD_CM_BASE	+ 400,	(400-430)公会命令基址)
	MESSAGE_ADD(	CMD_CM_CHARBASE,				CMD_CM_BASE	+ 430,	(430-450)角色命令基数)
	MESSAGE_ADD(	CMD_CM_SAY,						CMD_CM_BASE + 1,	视野内说话)
	MESSAGE_ADD(	CMD_CM_BEGINACTION,				CMD_CM_BASE + 6,	无)
	MESSAGE_ADD(	CMD_CM_ENDACTION,				CMD_CM_BASE + 7,	无)
	MESSAGE_ADD(	CMD_CM_SYNATTR,					CMD_CM_BASE + 8,	同步角色属性（同步属性的最终值）)
	MESSAGE_ADD(	CMD_CM_SYNSKILLBAG,				CMD_CM_BASE + 9,	同步技能栏)
	MESSAGE_ADD(	CMD_CM_DIE_RETURN,				CMD_CM_BASE + 10,	死亡复活)
	MESSAGE_ADD(	CMD_CM_SKILLUPGRADE,			CMD_CM_BASE + 11,	无)
	MESSAGE_ADD(	CMD_CM_PING,					CMD_CM_BASE + 15,	无)
	MESSAGE_ADD(	CMD_CM_REFRESH_DATA,			CMD_CM_BASE + 16,	无)
	MESSAGE_ADD(	CMD_CM_CHECK_PING,				CMD_CM_BASE + 17,	计算Ping)
	MESSAGE_ADD(	CMD_CM_MAP_MASK,				CMD_CM_BASE + 18,	无)
	MESSAGE_ADD(	CMD_CM_UPDATEHAIR,				CMD_CM_BASE + 20,	客户端请求更换发型)
	MESSAGE_ADD(	CMD_CM_TEAM_FIGHT_ASK,			CMD_CM_BASE + 21,	队伍挑战请求)
	MESSAGE_ADD(	CMD_CM_TEAM_FIGHT_ASR,			CMD_CM_BASE + 22,	队伍挑战应答(ANSWER))
	MESSAGE_ADD(	CMD_CM_ITEM_REPAIR_ASK,			CMD_CM_BASE + 23,	道具修理请求)
	MESSAGE_ADD(	CMD_CM_ITEM_REPAIR_ASR,			CMD_CM_BASE + 24,	道具修理应答)
	MESSAGE_ADD(	CMD_CM_ITEM_FORGE_ASK,			CMD_CM_BASE + 25,	道具精炼请求)
	MESSAGE_ADD(	CMD_CM_ITEM_FORGE_ASR,			CMD_CM_BASE + 26,	道具精炼应答)
	MESSAGE_ADD(	CMD_CM_TIGER_START,				CMD_CM_BASE + 27,	开启老虎机)
	MESSAGE_ADD(	CMD_CM_TIGER_STOP,				CMD_CM_BASE + 28,	停止老虎机)
	MESSAGE_ADD(	CMD_CM_ITEM_FORGE_CANACTION,	CMD_CM_BASE + 29,	有特殊任务已完成，可以做别的事。)
	MESSAGE_ADD(	CMD_CM_KITBAG_LOCK,				CMD_CM_BASE + 31,	背包锁定请求)
	MESSAGE_ADD(	CMD_CM_KITBAG_UNLOCK,			CMD_CM_BASE + 32,	背包解锁请求)
	MESSAGE_ADD(	CMD_CM_KITBAG_CHECK,			CMD_CM_BASE + 33,	检查背包锁定状态)
	MESSAGE_ADD(	CMD_CM_KITBAG_AUTOLOCK,			CMD_CM_BASE + 34,	下线自动锁定)
	MESSAGE_ADD(	CMD_CM_KITBAGTEMP_SYNC,			CMD_CM_BASE + 35,	同步临时背包)
	MESSAGE_ADD(	CMD_CM_STORE_OPEN_ASK,			CMD_CM_BASE + 41,	打开商城)
	MESSAGE_ADD(	CMD_CM_STORE_LIST_ASK,			CMD_CM_BASE + 42,	商城列表)
	MESSAGE_ADD(	CMD_CM_STORE_BUY_ASK,			CMD_CM_BASE + 43,	购买道具)
	MESSAGE_ADD(	CMD_CM_STORE_CHANGE_ASK,		CMD_CM_BASE + 44,	兑换代币)
	MESSAGE_ADD(	CMD_CM_STORE_QUERY,				CMD_CM_BASE + 45,	交易记录查询)
	MESSAGE_ADD(	CMD_CM_STORE_VIP,				CMD_CM_BASE + 46,	VIP)
	MESSAGE_ADD(	CMD_CM_STORE_AFFICHE,			CMD_CM_BASE + 47,	公告商品)
	MESSAGE_ADD(	CMD_CM_STORE_CLOSE,				CMD_CM_BASE + 48,	无)
	MESSAGE_ADD(	CMD_CM_BLACKMARKET_EXCHANGE_REQ,CMD_CM_BASE + 51,	黑市兑换)
	MESSAGE_ADD(	CMD_CM_CHEAT_CHECK,				CMD_CM_BASE + 52,	无)
	MESSAGE_ADD(	CMD_CM_VOLUNTER_LIST,			CMD_CM_BASE + 61,	显示志愿者列表)
	MESSAGE_ADD(	CMD_CM_VOLUNTER_ADD,			CMD_CM_BASE + 62,	添加到志愿者列表)
	MESSAGE_ADD(	CMD_CM_VOLUNTER_DEL,			CMD_CM_BASE + 63,	从列表中删除)
	MESSAGE_ADD(	CMD_CM_VOLUNTER_SEL,			CMD_CM_BASE + 64,	申请组队)
	MESSAGE_ADD(	CMD_CM_VOLUNTER_OPEN,			CMD_CM_BASE + 65,	打开志愿者面板)
	MESSAGE_ADD(	CMD_CM_VOLUNTER_ASR,			CMD_CM_BASE + 66,	志愿者组队应答)
	MESSAGE_ADD(	CMD_CM_MASTER_INVITE,			CMD_CM_BASE + 71,	拜师)
	MESSAGE_ADD(	CMD_CM_MASTER_ASR,				CMD_CM_BASE + 72,	无)
	MESSAGE_ADD(	CMD_CM_MASTER_DEL,				CMD_CM_BASE + 73,	无)
	MESSAGE_ADD(	CMD_CM_PRENTICE_DEL,			CMD_CM_BASE + 74,	无)
	MESSAGE_ADD(	CMD_CM_PRENTICE_INVITE,			CMD_CM_BASE + 75,	无)
	MESSAGE_ADD(	CMD_CM_PRENTICE_ASR,			CMD_CM_BASE + 76,	无)
	MESSAGE_ADD(	CMD_CM_LIFESKILL_ASR,			CMD_CM_BASE + 80,	生活技能用运，合成，分解等的请求)
	MESSAGE_ADD(	CMD_CM_LIFESKILL_ASK,			CMD_CM_BASE + 81,	生活技能用运，合成，分解等的确认)
	MESSAGE_ADD(	CMD_CM_BIDUP,					CMD_CM_BASE + 86,	无)
	MESSAGE_ADD(	CMD_CM_SAY2CAMP,				CMD_CM_BASE + 91,	无)
	MESSAGE_ADD(	CMD_CM_GM_SEND,					CMD_CM_BASE + 92,	无)
	MESSAGE_ADD(	CMD_CM_GM_RECV,					CMD_CM_BASE + 93,	无)
	MESSAGE_ADD(	CMD_CM_PK_CTRL,					CMD_CM_BASE + 94,	无)
	MESSAGE_ADD(	CMD_CM_ITEM_LOTTERY_ASK,		CMD_CM_BASE + 95,	道具精炼请求)
	MESSAGE_ADD(	CMD_CM_ITEM_LOTTERY_ASR,		CMD_CM_BASE + 96,	彩票设定应答)
	MESSAGE_ADD(	CMD_CM_CAPTAIN_CONFIRM_ASR,		CMD_CM_BASE + 97,	竞技场队长应答)
	MESSAGE_ADD(	CMD_CM_ITEM_AMPHITHEATER_ASK,	CMD_CM_BASE + 98,	投票发送)
	MESSAGE_ADD(	CMD_CM_ITEM_LOCK_ASK,			CMD_CM_BASE	+ 99,	无)
	MESSAGE_ADD(	CMD_CM_ITEM_UNLOCK_ASK,			CMD_CM_BASE + 100,	无)
	MESSAGE_ADD(	CMD_CM_SYNCHAR,					CMD_CM_BASE + 101, sync)
	MESSAGE_ADD(    CMD_CM_GETORIGNAMECOLOR,        CMD_CM_BASE + 102, GetOldColor)
	MESSAGE_ADD(	CMD_CM_CHANGETITLE,				CMD_CM_BASE + 103, ChangeTitle)
	MESSAGE_ADD(	CMD_CM_SYNGUILDCOLOR,			CMD_CM_BASE + 104, SynGuildColor)
	MESSAGE_ADD(	CMD_CM_GUILD_PUTNAME,		CMD_CM_GULDBASE	+ 1,	客户端输入公会名)
	MESSAGE_ADD(	CMD_CM_GUILD_TRYFOR,		CMD_CM_GULDBASE	+ 2,	申请加入公会)
	MESSAGE_ADD(	CMD_CM_GUILD_TRYFORCFM,		CMD_CM_GULDBASE	+ 3,	确认是否覆盖以前申请)
	MESSAGE_ADD(	CMD_CM_GUILD_LISTTRYPLAYER,	CMD_CM_GULDBASE	+ 4,	列出所有待批复玩家)
	MESSAGE_ADD(	CMD_CM_GUILD_APPROVE,		CMD_CM_GULDBASE	+ 5,	门猪批准申请人加入)
	MESSAGE_ADD(	CMD_CM_GUILD_REJECT,		CMD_CM_GULDBASE	+ 6,	门猪拒绝申请人加入)
	MESSAGE_ADD(	CMD_CM_GUILD_KICK,			CMD_CM_GULDBASE	+ 7,	无)
	MESSAGE_ADD(	CMD_CM_GUILD_LEAVE,			CMD_CM_GULDBASE	+ 8,	无)
	MESSAGE_ADD(	CMD_CM_GUILD_DISBAND,		CMD_CM_GULDBASE	+ 9,	无)
	MESSAGE_ADD(	CMD_CM_GUILD_MOTTO,			CMD_CM_GULDBASE	+ 10,	无)
	MESSAGE_ADD(	CMD_CM_GUILD_CHALLENGE,		CMD_CM_GULDBASE + 11,	挑战公会)
	MESSAGE_ADD(	CMD_CM_GUILD_LEIZHU,		CMD_CM_GULDBASE + 12,	抢擂主)
	MESSAGE_DEF(CMD_CM_GUILD_PERM, CMD_CM_GULDBASE + 13, Guild Perm)
	MESSAGE_ADD(	CMD_CM_LOGIN,				CMD_CM_CHARBASE + 1,	用户帐号登入(用户名/密码对认证))
	MESSAGE_ADD(	CMD_CM_LOGOUT,				CMD_CM_CHARBASE + 2,	用户帐号登出)
	MESSAGE_ADD(	CMD_CM_BGNPLAY,				CMD_CM_CHARBASE + 3,	用户选择角色开始玩游戏)
	MESSAGE_ADD(	CMD_CM_ENDPLAY,				CMD_CM_CHARBASE + 4,	用户结束玩游戏进入选/建/删角色画面)
	MESSAGE_ADD(	CMD_CM_NEWCHA,				CMD_CM_CHARBASE	+ 5,	用户新建角色)
	MESSAGE_ADD(	CMD_CM_DELCHA,				CMD_CM_CHARBASE	+ 6,	用户删除角色)
	MESSAGE_ADD(	CMD_CM_CANCELEXIT,			CMD_CM_CHARBASE + 7,	用户要求取消退出)
	MESSAGE_ADD(	CMD_CM_REQUESTNPC,			CMD_CM_ROLEBASE + 1,	客户端请求和NPC互动)
	MESSAGE_ADD(	CMD_CM_TALKPAGE,			CMD_CM_ROLEBASE + 2,	客户端请求与NPC对话页命令)
	MESSAGE_ADD(	CMD_CM_FUNCITEM,			CMD_CM_ROLEBASE + 3,	客户端请求指定功能选项操作)
	MESSAGE_ADD(	CMD_CM_REQUESTTRADE,		CMD_CM_ROLEBASE + 8,	客户端请求进行交易)
	MESSAGE_ADD(	CMD_CM_TRADEITEM,			CMD_CM_ROLEBASE + 9,	客户端请求交易物品)
	MESSAGE_ADD(	CMD_CM_REQUESTAGENCY,		CMD_CM_ROLEBASE + 10,	客户端请求npc代理交易)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_REQUEST,	CMD_CM_ROLEBASE + 12,	发起交易邀请)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_ACCEPT,	CMD_CM_ROLEBASE + 13,	接受交易邀请)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_REJECT,	CMD_CM_ROLEBASE + 14,	拒绝交易邀请)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_CANCEL,	CMD_CM_ROLEBASE + 15,	取消交易)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_ITEM,		CMD_CM_ROLEBASE + 16,	角色交易物品)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_VALIDATEDATA,CMD_CM_ROLEBASE + 17,	确认交易数据)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_VALIDATE,	CMD_CM_ROLEBASE + 18,	确认交易)
	MESSAGE_ADD(	CMD_CM_CHARTRADE_MONEY,		CMD_CM_ROLEBASE + 19,	拖动金钱)
	MESSAGE_ADD(	CMD_CM_MISSION,				CMD_CM_ROLEBASE + 22,	客户端请求任务处理)
	MESSAGE_ADD(	CMD_CM_MISSIONLIST,			CMD_CM_ROLEBASE + 23,	任务列表)
	MESSAGE_ADD(	CMD_CM_MISSIONTALK,			CMD_CM_ROLEBASE + 24,	任务对话)
	MESSAGE_ADD(	CMD_CM_MISLOG,				CMD_CM_ROLEBASE + 25,	任务日志)
	MESSAGE_ADD(	CMD_CM_MISLOGINFO,			CMD_CM_ROLEBASE + 26,	单个任务详细信息)
	MESSAGE_ADD(	CMD_CM_MISLOG_CLEAR,		CMD_CM_ROLEBASE + 27,	亲求删除一个任务)
	MESSAGE_ADD(	CMD_CM_STALL_ALLDATA,		CMD_CM_ROLEBASE + 30,	请求摆摊数据信息)
	MESSAGE_ADD(	CMD_CM_STALL_OPEN,			CMD_CM_ROLEBASE + 31,	请求打开摆摊货物信息)
	MESSAGE_ADD(	CMD_CM_STALL_BUY,			CMD_CM_ROLEBASE + 32,	请求购买摆摊货物)
	MESSAGE_ADD(	CMD_CM_STALL_CLOSE,			CMD_CM_ROLEBASE + 33,	请求收摊)
	MESSAGE_ADD(	CMD_CM_CREATE_BOAT,			CMD_CM_ROLEBASE + 38,	请求创建船)
	MESSAGE_ADD(	CMD_CM_UPDATEBOAT_PART,		CMD_CM_ROLEBASE + 39,	请求更换船只部件)
	MESSAGE_ADD(	CMD_CM_BOAT_CANCEL,			CMD_CM_ROLEBASE + 40,	请求取消建造船只)
	MESSAGE_ADD(	CMD_CM_BOAT_LUANCH,			CMD_CM_ROLEBASE + 41,	选择船只出海)
	MESSAGE_ADD(	CMD_CM_BOAT_BAGSEL,			CMD_CM_ROLEBASE + 42,	选择一艘船只货舱打包现有货物)
	MESSAGE_ADD(	CMD_CM_BOAT_SELECT,			CMD_CM_ROLEBASE + 43,	选择船只)
	MESSAGE_ADD(	CMD_CM_BOAT_GETINFO,		CMD_CM_ROLEBASE + 44,	获取船只信息)
	MESSAGE_ADD(	CMD_CM_ENTITY_EVENT,		CMD_CM_ROLEBASE + 45,	触发实体事件)
	MESSAGE_ADD(	CMD_CM_CREATE_PASSWORD2,	CMD_CM_ROLEBASE + 46,	创建二次密码)
	MESSAGE_ADD(	CMD_CM_UPDATE_PASSWORD2,	CMD_CM_ROLEBASE + 47,	更新二次密码)
	MESSAGE_ADD(	CMD_CM_READBOOK_START,		CMD_CM_ROLEBASE + 48,	开始读书)
	MESSAGE_ADD(	CMD_CM_READBOOK_CLOSE,		CMD_CM_ROLEBASE + 49,	结束读书)
	MESSAGE_ADD(	CMD_CM_SELECT_TIME_ASK,		CMD_CM_ROLEBASE + 50,	选择的离线时间)
	MESSAGE_ADD(	CMD_CM_BEHINDGENIUS_ASK,	CMD_CM_ROLEBASE + 51,	请求制造背后灵)
	MESSAGE_ADD(	CMD_CM_GET_OUTTIMEEXP,		CMD_CM_ROLEBASE + 52,	无)
	MESSAGE_ADD(	CMD_CM_SELECT_COIN_ASK,		CMD_CM_ROLEBASE + 53,	无)
	MESSAGE_ADD(	CMD_CM_REQUEST_ANYTIMETRADE,CMD_CM_ROLEBASE + 54,	随时交易)
	MESSAGE_ADD(	CMD_CM_REQUEST_JEWELRYUP_ASK,CMD_CM_ROLEBASE + 55,	宝石升级)
	MESSAGE_ADD(	CMD_CM_OPEN_CRYSTALTRADE_ASK,CMD_CM_ROLEBASE + 56,	打开水晶交易平台)
	MESSAGE_ADD(	CMD_CM_REQUEST_BUY_ASK,		CMD_CM_ROLEBASE + 57,	买入挂单)
	MESSAGE_ADD(	CMD_CM_REQUEST_SALE_ASK,	CMD_CM_ROLEBASE + 58,	卖出挂单)
	MESSAGE_ADD(	CMD_CM_REQUEST_CANCEL_ASK,	CMD_CM_ROLEBASE + 59,	取消挂单)
	MESSAGE_ADD(	CMD_CM_REQUEST_GETFLATMONEY,CMD_CM_ROLEBASE + 60,	取出平台账号上的钱)
	MESSAGE_ADD(	CMD_CM_REQUEST_REFRESH_ASK,	CMD_CM_ROLEBASE + 61,	请求刷新)
	MESSAGE_ADD(	CMD_CM_CHA_CONFIRM_CRYSTALTRADE,CMD_CM_ROLEBASE + 62,	玩家确认交易信息)
	MESSAGE_ADD(	CMD_CM_GARNER2_REORDER,			CMD_CM_ROLEBASE + 71,	客户端请求重排名)
	MESSAGE_ADD(	CMD_CM_ANTIINDULGENCE,			CMD_CM_ROLEBASE + 72,	防沉迷破解)
	MESSAGE_ADD(	XTRAP_CMD_STEP_TWO,				CMD_CM_ROLEBASE + 73,	无)
	MESSAGE_ADD(	XTRAP_MAP_FILE_CHANGE,			CMD_CM_ROLEBASE + 74,	无)
	MESSAGE_ADD(	CMD_CM_OPEN_CYCELMISSION,		CMD_CM_ROLEBASE + 75,	公会循环任务)//Add by sunny.sun 20090831
	MESSAGE_ADD(	CMD_MC_ROLEBASE,				CMD_MC_BASE	+ 300,	(300-400)任务系统命令基址)
	MESSAGE_ADD(	CMD_MC_GULDBASE,				CMD_MC_BASE	+ 400,	(400-430)公会命令基址)
	MESSAGE_ADD(	CMD_MC_CHARBASE,				CMD_MC_BASE	+ 430,	(430-450)角色命令基址)
	MESSAGE_ADD(	CMD_MC_SAY,						CMD_MC_BASE + 1,	视野内说话)
	MESSAGE_ADD(	CMD_MC_MAPCRASH,				CMD_MC_BASE	+ 3,	无)
	MESSAGE_ADD(	CMD_MC_CHABEGINSEE,				CMD_MC_BASE + 4,	无)
	MESSAGE_ADD(	CMD_MC_CHAENDSEE,				CMD_MC_BASE + 5,	无)
	MESSAGE_ADD(	CMD_MC_ITEMBEGINSEE,			CMD_MC_BASE + 6,	无)
	MESSAGE_ADD(	CMD_MC_ITEMENDSEE,				CMD_MC_BASE + 7,	无)
	MESSAGE_ADD(	CMD_MC_NOTIACTION,				CMD_MC_BASE + 8,	无)
	MESSAGE_ADD(	CMD_MC_SYNATTR,					CMD_MC_BASE + 9,	同步角色属性（同步属性的最终值）)
	MESSAGE_ADD(	CMD_MC_SYNSKILLBAG,				CMD_MC_BASE + 10,	同步技能栏)
	MESSAGE_ADD(	CMD_MC_SYNASKILLSTATE,			CMD_MC_BASE + 11,	同步角色状态)
	MESSAGE_ADD(	CMD_MC_PING,					CMD_MC_BASE + 15,	无)
	MESSAGE_ADD(	CMD_MC_ENTERMAP,				CMD_MC_BASE	+ 16,	GameServer通知Client进入地图，附带玩家的所有信息及其附属结构)
	MESSAGE_ADD(	CMD_MC_SYSINFO,					CMD_MC_BASE	+ 17,	系统消息提示命令，如玩家不在线，你还没有完成什么任务等等。)
	MESSAGE_ADD(	CMD_MC_ALARM,					CMD_MC_BASE	+ 18,	无)
	MESSAGE_ADD(	CMD_MC_TEAM,					CMD_MC_BASE + 19,	GameServer通知客户端某个队员的属性刷新(比如外观, HP,SP))
	MESSAGE_ADD(	CMD_MC_FAILEDACTION,			CMD_MC_BASE + 20,	请求的行动执行失败)
	MESSAGE_ADD(	CMD_MC_MESSAGE,					CMD_MC_BASE + 21,	提示信息)
	MESSAGE_ADD(	CMD_MC_ASTATEBEGINSEE,			CMD_MC_BASE + 22,	地面状态)
	MESSAGE_ADD(	CMD_MC_ASTATEENDSEE,			CMD_MC_BASE + 23,	无)
	MESSAGE_ADD(	CMD_MC_TLEADER_ID,				CMD_MC_BASE + 24,	GameServer通知客户端某个队员的队长信息)
	MESSAGE_ADD(	CMD_MC_CHA_EMOTION,				CMD_MC_BASE + 25,	GameServer触发指定角色做表情   )
	MESSAGE_ADD(	CMD_MC_QUERY_CHA,				CMD_MC_BASE + 26,	查询角色基本信息)
	MESSAGE_ADD(	CMD_MC_QUERY_CHAITEM,			CMD_MC_BASE + 27,	查询角色道具)
	MESSAGE_ADD(	CMD_MC_CALL_CHA,				CMD_MC_BASE + 28,	将角色召唤到自己身边)
	MESSAGE_ADD(	CMD_MC_GOTO_CHA,				CMD_MC_BASE + 29,	将自己传送到角色身边)
	MESSAGE_ADD(	CMD_MC_KICK_CHA,				CMD_MC_BASE + 30,	将角色踢下线)
	MESSAGE_ADD(	CMD_MC_SYNDEFAULTSKILL,			CMD_MC_BASE + 31,	同步默认技能)
	MESSAGE_ADD(	CMD_MC_ADD_ITEM_CHA,			CMD_MC_BASE + 32,	添加道具角色)
	MESSAGE_ADD(	CMD_MC_DEL_ITEM_CHA,			CMD_MC_BASE + 33,	删除道具角色)
	MESSAGE_ADD(	CMD_MC_QUERY_CHAPING,			CMD_MC_BASE + 34,	查询角色到GameServer逻辑层的ping值)
	MESSAGE_ADD(	CMD_MC_QUERY_RELIVE,			CMD_MC_BASE + 35,	咨询是否接受原地复活)
	MESSAGE_ADD(	CMD_MC_PREMOVE_TIME,			CMD_MC_BASE + 36,	预移动时间)
	MESSAGE_ADD(	CMD_MC_CHECK_PING,				CMD_MC_BASE + 37,	计算Ping)
	MESSAGE_ADD(	CMD_MC_MAP_MASK,				CMD_MC_BASE + 38,	无)
	MESSAGE_ADD(	CMD_MC_OPENHAIR,				CMD_MC_BASE + 39,	打开理发界面)
	MESSAGE_ADD(	CMD_MC_UPDATEHAIR_RES,			CMD_MC_BASE + 40,	更换发型的结果)
	MESSAGE_ADD(	CMD_MC_EVENT_INFO,				CMD_MC_BASE + 41,	同步事件信息)
	MESSAGE_ADD(	CMD_MC_SIDE_INFO,				CMD_MC_BASE + 42,	同步分边信息)
	MESSAGE_ADD(	CMD_MC_TEAM_FIGHT_ASK,			CMD_MC_BASE + 43,	队伍挑战请求)
	MESSAGE_ADD(	CMD_MC_ITEM_REPAIR_ASK,			CMD_MC_BASE + 44,	道具修理请求)
	MESSAGE_ADD(	CMD_MC_ITEM_REPAIR_ASR,			CMD_MC_BASE + 45,	道具修理应答)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_REPAIR,		CMD_MC_BASE + 46,	开始道具修理)
	MESSAGE_ADD(	CMD_MC_APPEND_LOOK,				CMD_MC_BASE + 47,	附加外观)
	MESSAGE_ADD(	CMD_MC_ITEM_FORGE_ASK,			CMD_MC_BASE + 48,	道具精炼请求)
	MESSAGE_ADD(	CMD_MC_ITEM_FORGE_ASR,			CMD_MC_BASE + 49,	道具精炼应答)
	MESSAGE_ADD(	CMD_MC_ITEM_USE_SUC,			CMD_MC_BASE + 50,	道具使用成功)
	MESSAGE_ADD(	CMD_MC_KITBAG_CAPACITY,			CMD_MC_BASE + 51,	背包容量)
	MESSAGE_ADD(	CMD_MC_ESPE_ITEM,				CMD_MC_BASE + 52,	特殊道具)
	MESSAGE_ADD(	CMD_MC_KITBAG_CHECK_ASR,		CMD_MC_BASE + 53,	背包锁定状态的应答)
	MESSAGE_ADD(	CMD_MC_KITBAGTEMP_SYNC,			CMD_MC_BASE + 54,	同步临时背包)
	MESSAGE_ADD(	CMD_MC_STORE_OPEN_ASR,			CMD_MC_BASE + 61,	打开商城)
	MESSAGE_ADD(	CMD_MC_STORE_LIST_ASR,			CMD_MC_BASE + 62,	商城列表)
	MESSAGE_ADD(	CMD_MC_STORE_BUY_ASR,			CMD_MC_BASE + 63,	购买道具)
	MESSAGE_ADD(	CMD_MC_STORE_CHANGE_ASR,		CMD_MC_BASE + 64,	兑换代币)
	MESSAGE_ADD(	CMD_MC_STORE_QUERY,				CMD_MC_BASE + 65,	交易记录查询)
	MESSAGE_ADD(	CMD_MC_STORE_VIP,				CMD_MC_BASE + 66,	VIP)
	MESSAGE_ADD(	CMD_MC_STORE_AFFICHE,			CMD_MC_BASE + 67,	公告商品)
	MESSAGE_ADD(	CMD_MC_POPUP_NOTICE,			CMD_MC_BASE + 68,	无)
	MESSAGE_ADD(	CMD_MC_BLACKMARKET_EXCHANGEDATA,	CMD_MC_BASE + 71,	黑市兑换数据)
	MESSAGE_ADD(	CMD_MC_BLACKMARKET_EXCHANGE_ASR,	CMD_MC_BASE + 72,	黑市兑换应答)
	MESSAGE_ADD(	CMD_MC_BLACKMARKET_EXCHANGEUPDATE,	CMD_MC_BASE + 73,	黑市兑换更新)
	MESSAGE_ADD(	CMD_MC_BLACKMARKET_TRADEUPDATE,	CMD_MC_BASE + 74,	黑市交易更新)
	MESSAGE_ADD(	CMD_MC_EXCHANGEDATA,			CMD_MC_BASE + 75,	普通兑换数据)
	MESSAGE_ADD(	CMD_MC_VOLUNTER_LIST,			CMD_MC_BASE + 81,	显示志愿者列表)
	MESSAGE_ADD(	CMD_MC_VOLUNTER_STATE,			CMD_MC_BASE + 82,	志愿者状态)
	MESSAGE_ADD(	CMD_MC_VOLUNTER_SEL,			CMD_MC_BASE + 83,	申请组队)
	MESSAGE_ADD(	CMD_MC_VOLUNTER_OPEN,			CMD_MC_BASE + 84,	打开志愿者面板)
	MESSAGE_ADD(	CMD_MC_VOLUNTER_ASK,			CMD_MC_BASE + 85,	志愿者组队申请)
	MESSAGE_ADD(	CMD_MC_LISTAUCTION,				CMD_MC_BASE + 86,	无)
	MESSAGE_ADD(	CMD_MC_MASTER_ASK,				CMD_MC_BASE + 91,	无)
	MESSAGE_ADD(	CMD_MC_PRENTICE_ASK,			CMD_MC_BASE + 92,	无)
	MESSAGE_ADD(	CMD_MC_CHAPLAYEFFECT,			CMD_MC_BASE + 93,	无)
	MESSAGE_ADD(	CMD_MC_SAY2CAMP,				CMD_MC_BASE + 96,	无)
	MESSAGE_ADD(	CMD_MC_GM_MAIL,					CMD_MC_BASE + 97,	无)
	MESSAGE_ADD(	CMD_MC_CHEAT_CHECK,				CMD_MC_BASE + 98,	无)
	MESSAGE_ADD(	CMD_CM_ITEM_LOCK_ASR,			CMD_MC_BASE	+	99,	无)
	MESSAGE_ADD(	CMD_MC_ITEM_UNLOCK_ASR,			CMD_MC_BASE	+	95,	无)

	// FEATURE: GUILD_BANL
	MESSAGE_ADD(CMD_MC_UPDATEGUILDBANKGOLD, CMD_MC_BASE + 120, Update Guild Bank Gold)

	MESSAGE_ADD(	CMD_MC_GUILD_GETNAME,		CMD_MC_GULDBASE	+ 1,	请求客户端输入公会名)
	MESSAGE_ADD(	CMD_MC_LISTGUILD,			CMD_MC_GULDBASE	+ 2,	命令客户端打开申请加入窗口并加入行会列表)
	MESSAGE_ADD(	CMD_MC_GUILD_TRYFORCFM,		CMD_MC_GULDBASE	+ 3,	确认是否覆盖以前申请)
	MESSAGE_ADD(	CMD_MC_GUILD_LISTTRYPLAYER,	CMD_MC_GULDBASE	+ 4,	列出所有待批复玩家)
	MESSAGE_ADD(	CMD_MC_GUILD_LISTCHALL,		CMD_MC_GULDBASE + 5,	查询公会挑战信息)
	MESSAGE_ADD(	CMD_MC_GUILD_MOTTO,			CMD_MC_GULDBASE	+ 10,	修改座右铭)
	MESSAGE_ADD(	CMD_MC_GUILD_LEAVE,			CMD_MC_GULDBASE + 11,	离开公会)
	MESSAGE_ADD(	CMD_MC_GUILD_KICK,			CMD_MC_GULDBASE + 12,	被踢出公会)
	MESSAGE_ADD(	CMD_MC_GUILD_INFO,			CMD_MC_GULDBASE + 13,	同步公会信息)
	MESSAGE_ADD(	CMD_MC_LOGIN,				CMD_MC_CHARBASE + 1,	无)
	MESSAGE_ADD(	CMD_MC_LOGOUT,				CMD_MC_CHARBASE + 2,	无)
	MESSAGE_ADD(	CMD_MC_BGNPLAY,				CMD_MC_CHARBASE + 3,	无)
	MESSAGE_ADD(	CMD_MC_ENDPLAY,				CMD_MC_CHARBASE + 4,	无)
	MESSAGE_ADD(	CMD_MC_NEWCHA,				CMD_MC_CHARBASE	+ 5,	无)
	MESSAGE_ADD(	CMD_MC_DELCHA,				CMD_MC_CHARBASE	+ 6,	无)
	MESSAGE_ADD(	CMD_MC_STARTEXIT,			CMD_MC_CHARBASE + 7	,	开始退出倒计时)
	MESSAGE_ADD(	CMD_MC_CANCELEXIT,			CMD_MC_CHARBASE + 8	,	取消退出倒计时)
	MESSAGE_ADD(	CMD_MC_CHAPSTR,				CMD_MC_CHARBASE	+ 10,	无)
	MESSAGE_ADD(	CMD_MC_CREATE_PASSWORD2,	CMD_MC_CHARBASE + 11,	无)
	MESSAGE_ADD(	CMD_MC_UPDATE_PASSWORD2,	CMD_MC_CHARBASE + 12,	无)
	MESSAGE_ADD(	CMD_MC_SYNCCHAR, CMD_MC_CHARBASE + 13, 无)
	MESSAGE_ADD(    CMD_MC_GETORIGCOLOR, CMD_MC_CHARBASE + 14, GetOrigColor)
	MESSAGE_ADD(    CMD_MC_CHANGETITLE,	CMD_MC_CHARBASE + 15, SetTitle)
	MESSAGE_ADD(	CMD_MC_SYNGUILDCOLOR, CMD_MC_CHARBASE + 16, SynGuildColor)
	MESSAGE_ADD(	CMD_MC_TALKPAGE,			CMD_MC_ROLEBASE + 1,	服务器向客户端发送对话信息)
	MESSAGE_ADD(	CMD_MC_FUNCPAGE,			CMD_MC_ROLEBASE + 2,	服务器向客户端发送功能选项页信息)
	MESSAGE_ADD(	CMD_MC_CLOSETALK,			CMD_MC_ROLEBASE + 3,	服务器向客户端发送关闭对话信息)
	MESSAGE_ADD(	CMD_MC_HELPINFO,			CMD_MC_ROLEBASE + 4,	服务器向客户端发送帮助信息)
	MESSAGE_ADD(	CMD_MC_TRADEPAGE,			CMD_MC_ROLEBASE + 5,	服务器向客户端发送交易信息)
	MESSAGE_ADD(	CMD_MC_TRADERESULT,			CMD_MC_ROLEBASE + 6,	服务器向客户端发送交易请求答复信息)
	MESSAGE_ADD(	CMD_MC_TRADE_DATA,			CMD_MC_ROLEBASE + 7,	NPC交易数据信息更新)
	MESSAGE_ADD(	CMD_MC_TRADE_ALLDATA,		CMD_MC_ROLEBASE + 8,	NPC交易数据信息更新)
	MESSAGE_ADD(	CMD_MC_TRADE_UPDATE,		CMD_MC_ROLEBASE + 9,	黑市商人交易信息更新)
	MESSAGE_ADD(	CMD_MC_EXCHANGE_UPDATE,		CMD_MC_ROLEBASE + 10,	黑市商人兑换信息更新)
	MESSAGE_ADD(	CMD_MC_CHARTRADE,			CMD_MC_ROLEBASE + 11,	服务器向客户端发送交易信息 )
	MESSAGE_ADD(	CMD_MC_CHARTRADE_REQUEST,	CMD_MC_ROLEBASE + 12,	服务器向客户端发送其他角色邀请交易信息)
	MESSAGE_ADD(	CMD_MC_CHARTRADE_CANCEL,	CMD_MC_ROLEBASE + 13,	服务器向客户端发送 )
	MESSAGE_ADD(	CMD_MC_CHARTRADE_ITEM,		CMD_MC_ROLEBASE + 14,	服务器向客户端角色发送交易的物品信息)
	MESSAGE_ADD(	CMD_MC_CHARTRADE_PAGE,		CMD_MC_ROLEBASE + 15,	服务器向客户端发送开始交易界面信息)
	MESSAGE_ADD(	CMD_MC_CHARTRADE_VALIDATEDATA,	CMD_MC_ROLEBASE + 16,	确认交易数据)
	MESSAGE_ADD(	CMD_MC_CHARTRADE_VALIDATE,	CMD_MC_ROLEBASE + 17,	确认交易)
	MESSAGE_ADD(	CMD_MC_CHARTRADE_RESULT,	CMD_MC_ROLEBASE + 18,	确认交易成功)
	MESSAGE_ADD(	CMD_MC_CHARTRADE_MONEY,		CMD_MC_ROLEBASE + 19,	拖动金钱操作)
	MESSAGE_ADD(	CMD_MC_MISSION,				CMD_MC_ROLEBASE + 22,	服务器向客户端发送任务列表页信息)
	MESSAGE_ADD(	CMD_MC_MISSIONLIST,			CMD_MC_ROLEBASE + 23,	任务列表)
	MESSAGE_ADD(	CMD_MC_MISSIONTALK,			CMD_MC_ROLEBASE + 24,	任务对话)
	MESSAGE_ADD(	CMD_MC_NPCSTATECHG,			CMD_MC_ROLEBASE + 25,	请求切换npc状态)
	MESSAGE_ADD(	CMD_MC_TRIGGER_ACTION,		CMD_MC_ROLEBASE + 26,	触发器动作)
	MESSAGE_ADD(	CMD_MC_MISPAGE,				CMD_MC_ROLEBASE + 27,	任务页信息)
	MESSAGE_ADD(	CMD_MC_MISLOG,				CMD_MC_ROLEBASE + 28,	任务日志)
	MESSAGE_ADD(	CMD_MC_MISLOGINFO,			CMD_MC_ROLEBASE + 29,	单个任务详细信息)
	MESSAGE_ADD(	CMD_MC_MISLOG_CHANGE,		CMD_MC_ROLEBASE + 30,	任务状态变化)
	MESSAGE_ADD(	CMD_MC_MISLOG_CLEAR,		CMD_MC_ROLEBASE + 31,	清除一个任务)
	MESSAGE_ADD(	CMD_MC_MISLOG_ADD,			CMD_MC_ROLEBASE + 32,	添加一个任务)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_FUSION,	CMD_MC_ROLEBASE + 33	,	开始熔合道具)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_UPGRADE,	CMD_MC_ROLEBASE + 34	,	开始道具升级)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_FORGE,	CMD_MC_ROLEBASE + 35	,	开始道具精炼)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_UNITE,	CMD_MC_ROLEBASE + 36	,	开始道具合成)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_MILLING,	CMD_MC_ROLEBASE + 37	,	开始道具打磨)
	MESSAGE_ADD(	CMD_MC_CREATEBOAT,			CMD_MC_ROLEBASE + 38,	创建船只)
	MESSAGE_ADD(	CMD_MC_UPDATEBOAT,			CMD_MC_ROLEBASE + 39,	改造船只)
	MESSAGE_ADD(	CMD_MC_UPDATEBOAT_PART,		CMD_MC_ROLEBASE + 40,	改造船只的部件)
	MESSAGE_ADD(	CMD_MC_BERTH_LIST,			CMD_MC_ROLEBASE + 41,	船只停泊列表)
	MESSAGE_ADD(	CMD_MC_BOAT_LIST,			CMD_MC_ROLEBASE + 42,	同步角色拥有的所有船只属性)
	MESSAGE_ADD(	CMD_MC_BOAT_ADD,			CMD_MC_ROLEBASE + 43,	添加一艘船)
	MESSAGE_ADD(	CMD_MC_BOAT_CLEAR,			CMD_MC_ROLEBASE + 44,	清除一艘船)
	MESSAGE_ADD(	CMD_MC_BOATINFO,			CMD_MC_ROLEBASE + 45,	同步船只属性信息)
	MESSAGE_ADD(	CMD_MC_BOAT_BAGLIST,		CMD_MC_ROLEBASE + 46,	显示可以打包的船只列表)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_EIDOLON_METEMPSYCHOSIS,	CMD_MC_ROLEBASE + 47,	开始精灵转生)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_EIDOLON_FUSION,	CMD_MC_ROLEBASE + 48,	开始精灵融合)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_PURIFY,	CMD_MC_ROLEBASE + 49	,	开始装备提纯)
	MESSAGE_ADD(	CMD_MC_ENTITY_BEGINESEE,	CMD_MC_ROLEBASE + 50,	同步视野实体信息)
	MESSAGE_ADD(	CMD_MC_ENTITY_ENDSEE,		CMD_MC_ROLEBASE + 51,	实体信息超出视野)
	MESSAGE_ADD(	CMD_MC_ENTITY_CHGSTATE,		CMD_MC_ROLEBASE + 52,	实体状态改变)
	MESSAGE_ADD(	CMD_MC_STALL_ALLDATA,		CMD_MC_ROLEBASE + 54,	查看摆摊所有信息)
	MESSAGE_ADD(	CMD_MC_STALL_UPDATE,		CMD_MC_ROLEBASE + 55,	摆摊货物更新信息)
	MESSAGE_ADD(	CMD_MC_STALL_DELGOODS,		CMD_MC_ROLEBASE + 56,	删除指定位置的货物)
	MESSAGE_ADD(	CMD_MC_STALL_CLOSE,			CMD_MC_ROLEBASE + 57,	摊主收摊)
	MESSAGE_ADD(	CMD_MC_STALL_START,			CMD_MC_ROLEBASE + 58,	成功摆摊)
	MESSAGE_ADD(	CMD_MC_STALL_NAME,			CMD_MC_ROLEBASE + 59,	摆摊名)
	MESSAGE_ADD(	CMD_MC_BICKER_NOTICE,		CMD_MC_ROLEBASE + 60,	闪动字体信息通知)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_ENERGY,	CMD_MC_ROLEBASE + 71	,	开始贝壳充电)
	MESSAGE_ADD(	CMD_MC_BEGIN_GET_STONE,		CMD_MC_ROLEBASE + 72	,	开始提取宝石)
	MESSAGE_ADD(	CMD_MC_BEGIN_TIGER,			CMD_MC_ROLEBASE + 73	,	精灵老虎机界面)
	MESSAGE_ADD(	CMD_MC_TIGER_ITEM_ID,		CMD_MC_ROLEBASE + 74	,	老虎机道具ID)
	MESSAGE_ADD(	CMD_MC_TIGER_STOP,			CMD_MC_ROLEBASE + 75	,	老虎机结束)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_FIX,		CMD_MC_ROLEBASE + 76	,	修理破锅)
	MESSAGE_ADD(	CMD_MC_BEGIN_GM_SEND,		CMD_MC_ROLEBASE + 77	,	发送GM邮件)
	MESSAGE_ADD(	CMD_MC_BEGIN_GM_RECV,		CMD_MC_ROLEBASE + 78	,	接收GM邮件)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_LOTTERY,	CMD_MC_ROLEBASE + 79	,	开始设置彩票)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_AMPHITHEATER,	CMD_MC_ROLEBASE + 80,	打开竞技场排行榜)
	MESSAGE_ADD(	CMD_MC_LEAVE_TIME_ASR,		CMD_MC_ROLEBASE + 81,	角色离线时间)
	MESSAGE_ADD(	CMD_MC_SELECT_TIME_ASR,		CMD_MC_ROLEBASE + 82,	获取离线经验消息回复)
	MESSAGE_ADD(	CMD_MC_BEHINDGENIUS_ASR,	CMD_MC_ROLEBASE + 83	,	背后灵制造应答)
	MESSAGE_ADD(	CMD_MC_BEGIN_ITEM_JEWELRYUP,CMD_MC_ROLEBASE + 84	,	弹开宝石升级界面)
	MESSAGE_ADD(	CMD_MC_OPEN_CRYSTALTRADE_ASR,CMD_MC_ROLEBASE + 85	,	打开水晶平台应答)
	MESSAGE_ADD(	CMD_MC_REQUEST_BUY_ASR,		CMD_MC_ROLEBASE + 86 ,	买入挂单应答)
	MESSAGE_ADD(	CMD_MC_REQUEST_SALE_ASR,	CMD_MC_ROLEBASE + 87 ,	卖出挂单应答)
	MESSAGE_ADD(	CMD_MC_REQUEST_CANCEL_ASR,	CMD_MC_ROLEBASE + 88 ,	取消挂单应答)
	MESSAGE_ADD(	CMD_MC_REQUEST_GETFLATMONEY,CMD_MC_ROLEBASE + 89 ,	取出平台上的钱应答)
	MESSAGE_ADD(	CMD_MC_REQUEST_REFRESH_ASR,	CMD_MC_ROLEBASE + 90 ,	请求刷新应答)
	MESSAGE_ADD(	CMD_MC_GET_CRYSTALSTATE,	CMD_MC_ROLEBASE + 91 ,	获取交易状态)
	MESSAGE_ADD(	CMD_MC_LIFESKILL_BGING,			CMD_MC_BASE + 100	,	生活技能开始)
	MESSAGE_ADD(	CMD_MC_LIFESKILL_ASR,			CMD_MC_BASE + 101	,	生活技能用运，合成，分解等的请求)
	MESSAGE_ADD(	CMD_MC_LIFESKILL_ASK,			CMD_MC_BASE + 102	,	生活技能用运，合成，分解等的确认)
	MESSAGE_ADD(	CMD_MC_ITEM_LOTTERY_ASK,		CMD_MC_BASE + 103,	彩票请求)
	MESSAGE_ADD(	CMD_MC_ITEM_LOTTERY_ASR,		CMD_MC_BASE + 104,	彩票应答)
	MESSAGE_ADD(	CMD_MC_CAPTAIN_ASK,				CMD_MC_BASE + 105,	竞技场队长确认请求)
	MESSAGE_ADD(	CMD_MC_ITEM_AMPHITHEATER_ASR,	CMD_MC_BASE + 106, 无)
	MESSAGE_ADD(	CMD_MC_REQUEST_JEWELRYUP_ASR,	CMD_MC_BASE + 107, 无)
	MESSAGE_ADD(	XTRAP_CMD_STEP_ONE,				CMD_MC_BASE + 108, 无)
	MESSAGE_ADD(	CMD_TM_ENTERMAP,				CMD_TM_BASE	+ 3	,	进地图，附带角色ID、进入地图的名字、位置(x,y))
	MESSAGE_ADD(	CMD_TM_GOOUTMAP,				CMD_TM_BASE + 4		,	出地图)
	MESSAGE_ADD(	CMD_TM_LOGIN_ACK,				CMD_TM_BASE + 5, 无)
	MESSAGE_ADD(	CMD_TM_CHANGE_PERSONINFO,		CMD_TM_BASE	+6	,	修改个人信息)
	MESSAGE_ADD(	CMD_TM_MAPENTRY,				CMD_TM_BASE + 7, 无)
	MESSAGE_ADD(	CMD_TM_MAPENTRY_NOMAP,			CMD_TM_BASE + 8, 无)
	MESSAGE_ADD(	CMD_TM_MAP_ADMIN,				CMD_TM_BASE + 9	,	管理员用地图控制命令)
	MESSAGE_ADD(	CMD_TM_STATE,					CMD_TM_BASE + 10,	服务器的状态（运行内存情况，版本）)
	MESSAGE_ADD(	CMD_MT_LOGIN,					CMD_MT_BASE + 1		,	GameServer登陆GateServer)
	MESSAGE_ADD(	CMD_MT_SWITCHMAP,				CMD_MT_BASE + 4		,	开始切换地图命令)
	MESSAGE_ADD(	CMD_MT_KICKUSER,				CMD_MT_BASE + 5		,	GameServer踢掉某个用户)
	MESSAGE_ADD(	CMD_MT_MAPENTRY,				CMD_MT_BASE + 6		,	地图入口)
	MESSAGE_ADD(	CMD_MT_PALYEREXIT,				CMD_MT_BASE + 8		,	通知Gate释放该用户资源)
	MESSAGE_ADD(	CMD_MT_MAP_ADMIN,				CMD_MT_BASE + 9	,	管理员用地图控制命令)
	MESSAGE_ADD(	CMD_MT_STATE,					CMD_MT_BASE + 10,	服务器的状态（运行内存情况，版本）)
	MESSAGE_ADD(	CMD_PM_TEAM,					CMD_PM_BASE + 1    ,	GroupServer发来的组队信息更新)
	MESSAGE_ADD(	CMD_PM_GUILD_DISBAND,			CMD_PM_BASE	+ 2		,	解散公会)
	MESSAGE_ADD(	CMD_PM_GUILDINFO,				CMD_PM_BASE + 4	,	GroupServer发来的公会同步信息)
	MESSAGE_ADD(	CMD_PM_GUILD_CHALLMONEY,		CMD_PM_BASE + 5    ,	将公会战投标的钱退给会长)
	MESSAGE_ADD(	CMD_PM_GUILD_CHALL_PRIZEMONEY,	CMD_PM_BASE + 6    ,	将公会战战奖励的钱给会长)
	MESSAGE_ADD(	CMD_PM_GARNER2_UPDATE,			CMD_PM_BASE +7, 无)
	MESSAGE_ADD(	CMD_PM_TEAM_CREATE,				CMD_PM_BASE + 8, 无)
	MESSAGE_ADD(	CMD_PM_SAY2ALL,					CMD_PM_BASE + 9, 无)
	MESSAGE_ADD(	CMD_PM_SAY2TRADE,				CMD_PM_BASE + 10, 无)
	MESSAGE_ADD(	CMD_PM_EXPSCALE,				CMD_PM_BASE + 11       ,	 防沉迷系统  影响玩家经验及掉宝率)
	MESSAGE_ADD(	CMD_PM_GUILD_INVITE,			CMD_PM_BASE + 12		,	公会邀请)

	// FEATURE: GUILD_BANK
	MESSAGE_ADD(CMD_PM_GUILDBANK, CMD_PM_BASE + 13, Guild Bank)


	MESSAGE_ADD(	CMD_MP_ENTERMAP,				CMD_MP_BASE	+ 1, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_APPROVE,			CMD_MP_BASE	+ 2, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_CREATE,			CMD_MP_BASE	+ 3, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_KICK,				CMD_MP_BASE	+ 4, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_LEAVE,				CMD_MP_BASE	+ 5, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_DISBAND,			CMD_MP_BASE	+ 6, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_MOTTO,				CMD_MP_BASE	+ 10, 无)
	MESSAGE_ADD(	CMD_MP_GUILD_CHALLMONEY,		CMD_MP_BASE + 13			,	将投标公会的钱退还会长角色)
	MESSAGE_ADD(	CMD_MP_GUILD_CHALL_PRIZEMONEY,	CMD_MP_BASE + 14    ,	将公会战奖励的的钱给会长角色)
	MESSAGE_ADD(	CMD_MP_GARNER2_UPDATE,			CMD_MP_BASE + 7, 无)
	MESSAGE_ADD(	CMD_MP_GARNER2_CGETORDER,		CMD_MP_BASE + 15, 无)
	MESSAGE_ADD(	CMD_MP_TEAM_CREATE,				CMD_MP_BASE + 16, 无)
	MESSAGE_ADD(	CMD_MP_MASTER_CREATE,			CMD_MP_BASE + 17, 无)
	MESSAGE_ADD(	CMD_MP_MASTER_DEL,				CMD_MP_BASE + 18, 无)
	MESSAGE_ADD(	CMD_MP_MASTER_FINISH,			CMD_MP_BASE + 19, 无)
	MESSAGE_ADD(	CMD_MP_SAY2ALL,					CMD_MP_BASE + 20, 无)
	MESSAGE_ADD(	CMD_MP_SAY2TRADE,				CMD_MP_BASE + 21, 无)
	MESSAGE_ADD(	CMD_MP_GM1SAY1,					CMD_MP_BASE + 22, 无)
	MESSAGE_ADD(	CMD_MP_GM1SAY,					CMD_MP_BASE + 23, 无)
	MESSAGE_ADD(	CMD_MP_GMBANACCOUNT,			CMD_MP_BASE + 24, GM封停刷屏账号)//Add by sunny.sun 20090828
	
	// FEATURE: GUILD_BANK
	MESSAGE_ADD(CMD_MP_GUILDBANK, CMD_MP_BASE + 25, Guild Bank)
	MESSAGE_ADD(CMD_MP_GUILDADDEXP, CMD_MP_BASE + 26, Guild Attr)
	MESSAGE_ADD(CMD_MP_GUILD_PERM, CMD_MP_BASE + 27, Guild Perm)

	MESSAGE_ADD(	CMD_TP_LOGIN,					CMD_TP_BASE + 1		,	GateServer到GroupServer进程间登陆)
	MESSAGE_ADD(	CMD_TP_LOGOUT,					CMD_TP_BASE + 2		,	GateServer到GroupServer进程间登出)
	MESSAGE_ADD(	CMD_TP_USER_LOGIN,				CMD_TP_BASE	+ 3		,	用户登入)
	MESSAGE_ADD(	CMD_TP_USER_LOGOUT,				CMD_TP_BASE + 4		,	用户登出)
	MESSAGE_ADD(	CMD_TP_BGNPLAY,					CMD_TP_BASE	+ 5		,	用户选择角色开始玩游戏)
	MESSAGE_ADD(	CMD_TP_ENDPLAY,					CMD_TP_BASE	+ 6		,	用户结束玩游戏进入选/建/删角色画面)
	MESSAGE_ADD(	CMD_TP_NEWCHA,					CMD_TP_BASE	+ 7		,	新建角色)
	MESSAGE_ADD(	CMD_TP_DELCHA,					CMD_TP_BASE	+ 8		,	删除角色)
	MESSAGE_ADD(	CMD_TP_PLAYEREXIT,				CMD_TP_BASE + 9		,	退出角色释放资源)
	MESSAGE_ADD(	CMD_TP_REQPLYLST,				CMD_TP_BASE	+ 10	,	请求本GateServer上的玩家地址列表)
	MESSAGE_ADD(	CMD_TP_DISC,					CMD_TP_BASE + 11, 无)
	MESSAGE_ADD(	CMD_TP_ESTOPUSER_CHECK,			CMD_TP_BASE + 12, 无)
	MESSAGE_ADD(	CMD_TP_CREATE_PASSWORD2,		CMD_TP_BASE + 13,	创建二次密码)
	MESSAGE_ADD(	CMD_TP_UPDATE_PASSWORD2,		CMD_TP_BASE + 14,	更新二次密码)
	MESSAGE_ADD(	CMD_TP_SYNC_PLYLST,				CMD_TP_BASE	+ 15	,	发送本GateServer上的玩家地址列表)
	MESSAGE_ADD(	CMD_PT_KICKUSER,				CMD_PT_BASE	+ 11, 无)
	MESSAGE_ADD(	CMD_PT_ESTOPUSER,				CMD_PT_BASE + 12,	禁言角色)
	MESSAGE_ADD(	CMD_PT_DEL_ESTOPUSER,			CMD_PT_BASE + 13,	解除禁言)

	MESSAGE_ADD(	CMD_PA_LOGIN,					CMD_PA_BASE + 2, 无)
	MESSAGE_ADD(	CMD_PA_USER_LOGIN,				CMD_PA_BASE + 4, 无)
	MESSAGE_ADD(	CMD_PA_USER_LOGOUT,				CMD_PA_BASE + 5, 无)
	MESSAGE_ADD(	CMD_PA_USER_DISABLE,			CMD_PA_BASE + 6, 无)
	MESSAGE_ADD(	CMD_PA_USER_LOGIN1,				CMD_PA_BASE + 13, 无)
	MESSAGE_ADD(	CMD_PA_USER_LOGIN2,				CMD_PA_BASE + 14, 无)
	MESSAGE_ADD(	CMD_PA_USER_BILLBGN,			CMD_PA_BASE + 20, 无)
	MESSAGE_ADD(	CMD_PA_USER_BILLEND,			CMD_PA_BASE + 21, 无)
	MESSAGE_ADD(	CMD_PA_GROUP_BILLEND_AND_LOGOUT,CMD_PA_BASE + 22, 无)
	MESSAGE_ADD(	CMD_PA_LOGOUT,					CMD_PA_BASE + 23, 无)
	MESSAGE_ADD(	CMD_PA_GMBANACCOUNT,			CMD_PA_BASE + 24, GM封停账号)//Add by sunny.sun 20090828

	MESSAGE_ADD(	CMD_AP_LOGIN,					CMD_AP_BASE + 2, 无)
	MESSAGE_ADD(	CMD_AP_USER_LOGIN,				CMD_AP_BASE + 3, 无)
	MESSAGE_ADD(	CMD_AP_RELOGIN,					CMD_AP_BASE + 4, 无)
	MESSAGE_ADD(	CMD_AP_KICKUSER,				CMD_AP_BASE	+ 11, 无)
	MESSAGE_ADD(	CMD_AP_USER_LOGIN1,				CMD_AP_BASE + 12, 无)
	MESSAGE_ADD(	CMD_AP_USER_LOGIN2,				CMD_AP_BASE + 13, 无)
	MESSAGE_ADD(	CMD_AP_EXPSCALE,				CMD_AP_BASE + 14, 防沉迷)
	MESSAGE_ADD(	CMD_MM_GATE_RELEASE,			CMD_MM_BASE + 1, 无)
	MESSAGE_ADD(	CMD_MM_GATE_CONNECT,			CMD_MM_BASE + 2, 无)
	MESSAGE_ADD(	CMD_MM_QUERY_CHA,				CMD_MM_BASE + 3	,	查询角色基本信息)
	MESSAGE_ADD(	CMD_MM_QUERY_CHAITEM,			CMD_MM_BASE + 4	,	查询角色道具信息)
	MESSAGE_ADD(	CMD_MM_CALL_CHA,				CMD_MM_BASE + 5	,	将角色召唤到自己身边)
	MESSAGE_ADD(	CMD_MM_GOTO_CHA,				CMD_MM_BASE + 6	,	将自己传送到角色身边)
	MESSAGE_ADD(	CMD_MM_KICK_CHA,				CMD_MM_BASE + 7	,	将角色踢下线)
	MESSAGE_ADD(	CMD_MM_GUILD_REJECT,			CMD_MM_BASE + 8	,	拒绝加入公会申请通知命令)
	MESSAGE_ADD(	CMD_MM_GUILD_APPROVE,			CMD_MM_BASE + 9	,	拒绝加入公会申请通知命令)
	MESSAGE_ADD(	CMD_MM_GUILD_KICK,				CMD_MM_BASE	+ 10,	从公会里面剔除某人)
	MESSAGE_ADD(	CMD_MM_GUILD_DISBAND,			CMD_MM_BASE	+ 11,	解散公会)
	MESSAGE_ADD(	CMD_MM_QUERY_CHAPING,			CMD_MM_BASE + 12,	查询角色到GameServer逻辑层的ping值)
	MESSAGE_ADD(	CMD_MM_NOTICE,					CMD_MM_BASE + 13,	系统通告)
	MESSAGE_ADD(	CMD_MM_GUILD_MOTTO,				CMD_MM_BASE + 14,	更新公会座佑名)
	MESSAGE_ADD(	CMD_MM_DO_STRING,				CMD_MM_BASE + 15,	执行脚本)
	MESSAGE_ADD(	CMD_MM_CHA_NOTICE,				CMD_MM_BASE + 16,	对指定玩家的系统通告)
	MESSAGE_ADD(	CMD_MM_LOGIN,					CMD_MM_BASE + 17,	玩家登陆游戏)
	MESSAGE_ADD(	CMD_MM_GUILD_CHALL_PRIZEMONEY,	CMD_MM_BASE + 18,	退还工会战的费用)
	MESSAGE_ADD(	CMD_MM_ADDCREDIT,				CMD_MM_BASE + 19,	增加声望)
	MESSAGE_ADD(	CMD_MM_STORE_BUY,				CMD_MM_BASE + 20,	购买商城商品)
	MESSAGE_ADD(	CMD_MM_ADDMONEY,				CMD_MM_BASE + 21, 无)
	MESSAGE_ADD(	CMD_MM_AUCTION,					CMD_MM_BASE + 22, 无)
	MESSAGE_ADD(	CMD_MM_NOTICETOCHA,				CMD_MM_BASE + 23,	水晶交易通知不在同一服务器的交易者)
	MESSAGE_ADD(	CMD_MM_EXCHEXTERNVALUE,			CMD_MM_BASE + 24,	脚本改变全局变量)
	MESSAGE_ADD(	CMD_MM_NOTICETRADER,			CMD_MM_BASE + 25,	通知交易者)

	// FEATURE: GUILD_BANK
	MESSAGE_ADD(CMD_MM_UPDATEGUILDBANK, CMD_MM_BASE + 26, Update Guild Bank)
	MESSAGE_ADD(CMD_MM_UPDATEGUILDBANKGOLD, CMD_MM_BASE + 27, Update Guild Bank Gold)

	MESSAGE_ADD(	CMD_CP_TEAM_INVITE,			CMD_CP_BASE	+ 1		,	邀请组队)
	MESSAGE_ADD(	CMD_CP_TEAM_ACCEPT,			CMD_CP_BASE	+ 2		,	确认组队)
	MESSAGE_ADD(	CMD_CP_TEAM_REFUSE,			CMD_CP_BASE	+ 3		,	拒绝组队)
	MESSAGE_ADD(	CMD_CP_TEAM_LEAVE,			CMD_CP_BASE	+ 4		,	离开组队)
	MESSAGE_ADD(	CMD_CP_TEAM_KICK,			CMD_CP_BASE + 5		,	踢出组队)
	MESSAGE_ADD(	CMD_CP_FRND_INVITE,			CMD_CP_BASE	+ 11	,	好友邀请)
	MESSAGE_ADD(	CMD_CP_FRND_ACCEPT,			CMD_CP_BASE	+ 12	,	好友接收)
	MESSAGE_ADD(	CMD_CP_FRND_REFUSE,			CMD_CP_BASE	+ 13	,	好友拒绝)
	MESSAGE_ADD(	CMD_CP_FRND_DELETE,			CMD_CP_BASE	+ 14	,	好友删除)
	MESSAGE_ADD(	CMD_CP_FRND_MOVE_GROUP,		CMD_CP_BASE	+ 15	,	改变好友所属分组)
	MESSAGE_ADD(	CMD_CP_FRND_REFRESH_INFO,	CMD_CP_BASE	+ 16	,	在自己的客户端刷新别人（好友、队友、同门、路人、陌生人）的个人信息)
	MESSAGE_ADD(	CMD_CP_CHANGE_PERSONINFO,	CMD_CP_BASE	+ 17	,	改变玩家自己的头像等个人信息)
	MESSAGE_ADD(	CMD_CP_FRND_DEL_GROUP,		CMD_CP_BASE	+ 18, 无)
	MESSAGE_ADD(	CMD_CP_FRND_ADD_GROUP,		CMD_CP_BASE	+ 19, 无)
	MESSAGE_ADD(	CMD_CP_FRND_CHANGE_GROUP,	CMD_CP_BASE	+ 20, 无)
	MESSAGE_ADD(	CMD_CP_QUERY_PERSONINFO,	CMD_CP_BASE	+ 21, 无)
	MESSAGE_ADD(	CMD_CP_PING,					CMD_CP_BASE	+ 25, 无)
	MESSAGE_ADD(	CMD_CP_REPORT_WG,				CMD_CP_BASE + 26,	报告发现使用外挂)
	MESSAGE_ADD(	CMD_CP_MASTER_REFRESH_INFO,		CMD_CP_BASE	+ 31	,	在自己的客户端刷新师父的个人信息)
	MESSAGE_ADD(	CMD_CP_PRENTICE_REFRESH_INFO,	CMD_CP_BASE	+ 32	,	在自己的客户端刷新徒弟的个人信息)
	MESSAGE_ADD(	CMD_CP_GUILD_INVITE,			CMD_CP_BASE + 33, 无)
	MESSAGE_ADD(	CMD_CP_GUILD_ACCEPT,			CMD_CP_BASE + 34, 无)
	MESSAGE_ADD(	CMD_CP_GUILD_REFUSE,			CMD_CP_BASE + 35, 无)
	MESSAGE_ADD(	CMD_CP_GM1SAY,				CMD_CP_BASE	+ 400		,	GM的全服广播)
	MESSAGE_ADD(	CMD_CP_SAY2TRADE,			CMD_CP_BASE	+ 401		,	交易频道)
	MESSAGE_ADD(	CMD_CP_SAY2ALL,				CMD_CP_BASE + 402		,	整个游戏世界广播)
	MESSAGE_ADD(	CMD_CP_SAY2YOU,				CMD_CP_BASE	+ 403		,	P2P聊天(玩家对玩家))
	MESSAGE_ADD(	CMD_CP_SAY2TEM,				CMD_CP_BASE	+ 404		,	组队聊天)
	MESSAGE_ADD(	CMD_CP_SAY2GUD,				CMD_CP_BASE	+ 405		,	行会(Guild)聊天)
	MESSAGE_ADD(	CMD_CP_SESS_CREATE,			CMD_CP_BASE	+ 406		,	会话建立)
	MESSAGE_ADD(	CMD_CP_SESS_SAY,			CMD_CP_BASE	+ 407		,	会话说话)
	MESSAGE_ADD(	CMD_CP_SESS_ADD,			CMD_CP_BASE	+ 408		,	会话添加人员)
	MESSAGE_ADD(	CMD_CP_SESS_LEAVE,			CMD_CP_BASE	+ 409		,	离开会话)
	MESSAGE_ADD(	CMD_CP_REFUSETOME,			CMD_CP_BASE	+ 410		,	打开接收私聊开关)
	MESSAGE_ADD(	CMD_CP_GM1SAY1,				CMD_CP_BASE	+ 411		,	滚动广播)
	MESSAGE_ADD(	CMD_CP_GMSAY,				CMD_CP_BASE	+ 412		,	特殊命令执行)

	// FEATURE: GUILD_BANK
	MESSAGE_ADD(CMD_CP_GUILDBANK, CMD_CP_BASE + 414, Guild Bank)
	MESSAGE_ADD(CMD_CP_GUILDATTR, CMD_CP_BASE + 416, Guild Attr)
	MESSAGE_ADD(CMD_CP_GUILDNAMECOLOR, CMD_CP_BASE + 417, Guild Color)


	MESSAGE_ADD(	CMD_PC_TEAM_INVITE,			CMD_PC_BASE	+ 1			,	通知客户端有人邀请组队)
	MESSAGE_ADD(	CMD_PC_TEAM_REFRESH,		CMD_PC_BASE	+ 2			,	通知客户端组队变化的信息，使用CMD_PM_TEAM定义的子类型)
	MESSAGE_ADD(	CMD_PC_TEAM_CANCEL,			CMD_PC_BASE	+ 3			,	服务器因为超时或成员数已满等原因通知被邀请方取消本次邀请)
	MESSAGE_ADD(	CMD_PC_FRND_INVITE,			CMD_PC_BASE	+ 11, 无)
	MESSAGE_ADD(	CMD_PC_FRND_REFRESH,		CMD_PC_BASE	+ 12, 无)
	MESSAGE_ADD(	CMD_PC_FRND_CANCEL,			CMD_PC_BASE	+ 13, 无)
	MESSAGE_ADD(	CMD_PC_FRND_MOVE_GROUP,		CMD_PC_BASE + 15	,	改变好友分组成功)
	MESSAGE_ADD(	CMD_PC_FRND_REFRESH_INFO,	CMD_PC_BASE	+ 16	,	刷新好友个人信息)
	MESSAGE_ADD(	CMD_PC_CHANGE_PERSONINFO,	CMD_PC_BASE	+ 17	,	改变玩家自己的头像等个人信息)
	MESSAGE_ADD(	CMD_PC_FRND_DEL_GROUP,		CMD_PC_BASE + 18	,	删除好友分组成功)
	MESSAGE_ADD(	CMD_PC_FRND_ADD_GROUP,		CMD_PC_BASE + 19	,	新增好友分组成功)
	MESSAGE_ADD(	CMD_PC_FRND_CHANGE_GROUP,	CMD_PC_BASE + 20	,	改变好友分组成功)
	MESSAGE_ADD(	CMD_PC_QUERY_PERSONINFO,	CMD_PC_BASE	+ 21	,	改变玩家自己的头像等个人信息)
	MESSAGE_ADD(	CMD_PC_PING,				CMD_PC_BASE	+ 25, 无)
	MESSAGE_ADD(	CMD_PC_GUILD,				CMD_PC_BASE	+ 30, 无)
	MESSAGE_ADD(	CMD_PC_GUILD_INVITE,		CMD_PC_BASE	+ 31, 无)
	MESSAGE_ADD(	CMD_PC_GUILD_CANCEL,		CMD_PC_BASE	+ 33, 无)
	MESSAGE_ADD(	CMD_PC_MASTER_REFRESH,	CMD_PC_BASE	+ 41, 无)
	MESSAGE_ADD(	CMD_PC_MASTER_CANCEL,	CMD_PC_BASE	+ 42, 无)
	MESSAGE_ADD(	CMD_PC_MASTER_REFRESH_INFO,	CMD_PC_BASE	+ 43	,	刷新师父个人信息)
	MESSAGE_ADD(	CMD_PC_PRENTICE_REFRESH_INFO,CMD_PC_BASE	+ 44	,	刷新徒弟个人信息)
	MESSAGE_ADD(	CMD_PC_GM1SAY,				CMD_PC_BASE	+ 400		,	GM的全服广播)
	MESSAGE_ADD(	CMD_PC_SAY2TRADE,			CMD_PC_BASE	+ 401		,	交易频道)
	MESSAGE_ADD(	CMD_PC_SAY2ALL,				CMD_PC_BASE + 402		,	整个游戏世界广播)
	MESSAGE_ADD(	CMD_PC_SAY2YOU,				CMD_PC_BASE	+ 403		,	P2P聊天(玩家对玩家))
	MESSAGE_ADD(	CMD_PC_SAY2TEM,				CMD_PC_BASE	+ 404		,	组队聊天)
	MESSAGE_ADD(	CMD_PC_SAY2GUD,				CMD_PC_BASE	+ 405		,	行会(Guild)聊天)
	MESSAGE_ADD(	CMD_PC_SESS_CREATE,			CMD_PC_BASE	+ 406		,	会话建立)
	MESSAGE_ADD(	CMD_PC_SESS_SAY,			CMD_PC_BASE	+ 407		,	会话说话)
	MESSAGE_ADD(	CMD_PC_SESS_ADD,			CMD_PC_BASE	+ 408		,	会话添加人员)
	MESSAGE_ADD(	CMD_PC_SESS_LEAVE,			CMD_PC_BASE	+ 409		,	离开会话)
	MESSAGE_ADD(	CMD_PC_GM1SAY1,				CMD_PC_BASE	+ 411		,	滚动广播)

	// FEATURE: GUILD_BANK
	MESSAGE_ADD(CMD_PC_ERRMSG, CMD_PC_BASE + 414, Error Message)
	MESSAGE_ADD(CMD_PC_UPDATEGUILDATTR, CMD_PC_BASE + 416, Guild Perm)
	MESSAGE_ADD(CMD_PC_GUILDNAMECOLOR, CMD_PC_BASE + 417, Guild Color)

	MESSAGE_ADD(	CMD_PC_GARNER2_ORDER,		CMD_PC_BASE +101, 无)
	MESSAGE_ADD(	CMD_OS_LOGIN,				CMD_OS_BASE + 1			,	登录)
	MESSAGE_ADD(	CMD_OS_PING,				CMD_OS_BASE + 2			,	检测命令)
	MESSAGE_ADD(	CMD_SO_LOGIN,				CMD_SO_BASE + 1			,	登录命令)
	MESSAGE_ADD(	CMD_SO_PING,				CMD_SO_BASE + 2			,	检测命令)
	MESSAGE_ADD(	CMD_SO_WARING,				CMD_SO_BASE + 3			,	警告命令)
	MESSAGE_ADD(	CMD_SO_EXCEPTION,			CMD_SO_BASE + 4		,	异常命令)
	MESSAGE_ADD(	CMD_SO_ON_LINE,				CMD_SO_BASE + 5			,	上线命令)
	MESSAGE_ADD(	CMD_SO_OFF_LINE,			CMD_SO_BASE + 6			,	下线命令)
	MESSAGE_ADD(	CMD_SO_ENTER_MAP,			CMD_SO_BASE + 7			,	进入地图命令)
	MESSAGE_ADD(	CMD_SO_LEAVE_MAP,			CMD_SO_BASE + 8			,	离开地图命令)
	MESSAGE_ADD(	CMD_AB_LOGIN,				CMD_AB_BASE + 1			,	登录)
	MESSAGE_ADD(	CMD_AB_LOGOUT,				CMD_AB_BASE + 2			,	登出)
	MESSAGE_ADD(	CMD_AB_USER_LOGINT,			CMD_AB_BASE + 3			,	玩家登录)
	MESSAGE_ADD(	CMD_AB_USER_LOGOUT,			CMD_AB_BASE + 4			,	玩家登出)
	MESSAGE_ADD(	CMD_BA_USER_TIME,			CMD_BA_BASE + 1			,	玩家时间通知)
	MESSAGE_ADD(	CMD_BA_KILL_USER,			CMD_BA_BASE + 2			,	踢掉玩家（目前两种情况1.上线时玩家已经过了5小时健康时间2.玩家认证失败）)
}

inline static void ClearMessage()
{
	MsgMap.clear();
}

#endif
