/* Generated by Together */
/*
*		产生的ID从1开始，ID(0)表示无效ID，是一个无效值。
*/
#ifndef IDENTITY_H
#define IDENTITY_H

#include "GameAppNet.h"

class CGameApp;

/**
 * @class Identity 
 * @author 
 * @brief 唯一标示，产生的ID从1开始，ID(0)表示无效ID，是一个无效值。
 *		
 * @bug 多线程会重复
 */
class Identity
{
	friend class CGameApp;
public:

	Identity():m_maxID(0){}

	/**
	* @brif 取得ID
	*
	* @return uLong ID
	*/
	dbc::uLong GetID()
	{
		return ++m_maxID;
	}

private:
	dbc::uLong m_maxID;
};
#endif //IDENTITY_H
